LookUp Event Handling: rewrite
DevExpress/devextreme-demos pull request #1172
Opened 2021-08-23 08:48 UTC by pavel-2020

2021-08-23 09:40 UTC, AlexJameson commented on JSDemos/Demos/Lookup/EventHandling/description.md
> +[valueChanged](/Documentation/ApiReference/UI_Components/dxLookup/Events/#valueChanged) event, use the [on(eventName, eventHandler)](/Documentation/ApiReference/UI_Components/dxLookup/Methods/#oneven
Just a reminder - you can create a separate description for each approach. Vue developers are not interested in React, Angular devs in jQuery and so on.

2021-08-23 09:40 UTC, AlexJameson commented on JSDemos/Demos/Lookup/EventHandling/description.md
> +To handle the Lookup's value change, specify the [onValueChanged](/Documentation/ApiReference/UI_Components/dxLookup/Configuration/#onValueChanged) handler. This demo uses it to display the picture a
```suggestion
To handle the Lookup's value change, specify the [onValueChanged](/Documentation/ApiReference/UI_Components/dxLookup/Configuration/#onValueChanged) function. This demo uses it to display the picture and text for the selected item.
```

2021-08-23 09:40 UTC, AlexJameson commented on JSDemos/Demos/Lookup/EventHandling/description.md
> +[valueChangeEvent](/Documentation/ApiReference/UI_Components/dxLookup/Configuration/#valueChangeEvent) property. The default events are input, change, and keyup.
```suggestion
To specify the <a href="https://developer.mozilla.org/en-US/docs/Web/Events" target="_blank">DOM events</a> after which search results should be updated, use the [valueChangeEvent](/Documentation/ApiReference/UI_Components/dxLookup/Configuration/#valueChangeEvent) property. The default events are *"input"*, *"change"*, and *"keyup"*.
```

2021-08-30 14:59 UTC, RomanTsukanov commented on JSDemos/Demos/Lookup/EventHandling/description.md
> +[valueChanged](/Documentation/ApiReference/UI_Components/dxLookup/Events/#valueChanged) event, use the [on(eventName, eventHandler)](/Documentation/ApiReference/UI_Components/dxLookup/Methods/#oneven
The scenario with `on` is rare. Two-way data bindings are not about event handling. Let's remove this paragraph entirely.

```suggestion
```

2021-08-30 14:59 UTC, RomanTsukanov commented on JSDemos/Demos/Lookup/EventHandling/description.md
> +The Lookup applies the selection instantly. If you want users to click the Apply button instead, set the [applyValueMode](/Documentation/ApiReference/UI_Components/dxLookup/Configuration/#applyValueM
We haven't mentioned selection yet, so this paragraph looks out of place. Why do we even mention this property? It's not in the demo, and it is related to the topic only barely.

2021-08-30 14:59 UTC, RomanTsukanov commented on JSDemos/Demos/Lookup/EventHandling/description.md
> +To specify the DOM events after which search results should be updated, use the
"search results"? Isn't `valueChangeEvent` specify an event on which to the change the `value` property?

2021-09-16 07:33 UTC, RomanTsukanov requested changes

2021-09-16 07:33 UTC, RomanTsukanov commented on JSDemos/Demos/Lookup/EventHandling/description.md
> +The Lookup applies the selection instantly. If you want users to click the Apply button instead, set the [applyValueMode](/Documentation/ApiReference/UI_Components/dxLookup/Configuration/#applyValueM
> In this demo, you can use a switch to toggle this property.

When will this functionality be added to the demo?

```suggestion
The Lookup applies the selected value instantly. If you want users to click the Apply button instead, set the [applyValueMode](/Documentation/ApiReference/UI_Components/dxLookup/Configuration/#applyValueMode) property to *"useButtons"*. In this demo, you can use a switch to toggle this property.
```

2021-09-16 12:35 UTC, RomanTsukanov approved these changes, later dismissed

2021-09-16 14:38 UTC, dmitry-eliseev-devexpress commented on JSDemos/Demos/Lookup/EventHandling/description.md
> +To handle the Lookup's value change, specify the [onValueChanged](/Documentation/ApiReference/UI_Components/dxLookup/Configuration/#onValueChanged) function. This demo uses it to display the picture
Where should I specify the mentioned function?

2021-09-16 14:38 UTC, dmitry-eliseev-devexpress commented on JSDemos/Demos/Lookup/EventHandling/description.md
> +The Lookup applies the selected value instantly. If you want users to click the Apply button instead, set the [applyValueMode](/Documentation/ApiReference/UI_Components/dxLookup/Configuration/#applyV
> If you want users to click the Apply button instead

This is not an end in itself. The thing is that the described option allows you to delay the effects of your change until a click on the "Apply" button.

> This functionality **is not used** in this demo.

This passive voice is totally avoidable from the look of it. For example:

> This demo does not show this functionality.

2021-09-18 04:29 UTC, dirk-pieterse submitted a review, later dismissed

2021-09-18 04:29 UTC, dirk-pieterse commented on JSDemos/Demos/Lookup/EventHandling/description.md
> +To handle the Lookup component's value change, specify the [onValueChanged](/Documentation/ApiReference/UI_Components/dxLookup/Configuration/#onValueChanged) function. This demo uses it to display th
```suggestion
To handle changes to the Lookup component's value, specify the [onValueChanged](/Documentation/ApiReference/UI_Components/dxLookup/Configuration/#onValueChanged) function. This demo uses it to display a picture and text for the selected item.
```

2021-09-23 08:19 UTC, RomanTsukanov approved these changes

2021-09-23 08:21 UTC, merged