Datagrid signalrservice
DevExpress/devextreme-demos pull request #1274
Opened 2021-09-07 18:48 UTC by jacksonrr3

2021-09-08 05:28 UTC, alexserov approved these changes, later dismissed

2021-09-08 09:03 UTC, nightskylark requested changes

2021-09-08 09:03 UTC, nightskylark commented on JSDemos/Demos/DataGrid/SignalRService/test-code.js
> +    dataGrid.option = function () {};
Leave a note to explain hack

2021-09-09 08:55 UTC, nightskylark commented on JSDemos/Demos/DataGrid/SignalRService/test-code.js
> +    // ensure, that 'React' can't restore `DataSourse`.
```suggestion
    // NOTE: Ensure, that 'React' can't restore `DataSourse`.
```

2021-09-09 14:41 UTC, alexserov approved these changes

2021-09-09 15:05 UTC, nightskylark approved these changes

2021-09-09 15:20 UTC, merged