Rewrite the Chart - Points Aggregation demo description(T929184)
DevExpress/devextreme-demos pull request #129
Opened 2020-09-15 15:57 UTC by AlexJameson

2020-09-17 12:08 UTC, RomanTsukanov requested changes

2020-09-17 12:08 UTC, RomanTsukanov commented on JSDemos/Demos/Charts/PointsAggregationFinancialChart/description.md
> +The **Chart** widget can aggregate data represented by series points. To enable this feature, set the **aggregation**.[enabled](/Documentation/ApiReference/Data_Visualization_Widgets/dxChart/Configur
```suggestion
The **Chart** widget can aggregate series points. To enable this feature, set the **aggregation**.[enabled](/Documentation/ApiReference/Data_Visualization_Widgets/dxChart/Configuration/series/aggregation/#enabled) option of a [series](/Documentation/ApiReference/Data_Visualization_Widgets/dxChart/Configuration/series/) to **true**. 
```

2020-09-17 12:08 UTC, RomanTsukanov commented on JSDemos/Demos/Charts/PointsAggregationFinancialChart/description.md
> +In this demo, the chart's [visual range](/Documentation/ApiReference/Data_Visualization_Widgets/dxChart/Configuration/argumentAxis/visualRange/) depends on the [RangeSelector](/Documentation/ApiRefer
It is better to being from the beginning:

```suggestion
In this demo, the **Chart** is bound to the [RangeSelector](/Documentation/ApiReference/Data_Visualization_Widgets/dxRangeSelector/) component. When you narrow down the selection range, the chart zooms in, and the series points become less aggregated. The converse is also true: when the selected range is wider, the degree of aggregation is higher.
```

I also removed the last sentence for two reasons: 1) `aggregationInterval` is not the only means of controlling the degree of aggregation - there's also `aggregationGroupWidth`; 2) this demo has an option called `aggregationInterval` set for the RangeSelector, and it is not the same option. I think it is better to send the user to the `aggregation` description and let him find out the details from there. Hence, the suggestion for the paragraph below.

2020-09-17 12:08 UTC, RomanTsukanov commented on JSDemos/Demos/Charts/PointsAggregationFinancialChart/description.md
> +Refer to the [aggregation](/Documentation/ApiReference/Data_Visualization_Widgets/dxChart/Configuration/series/aggregation/) option description to see possible options for different series types.
```suggestion
Aggregation on zoom is only one use case for this feature. Refer to the [aggregation](/Documentation/ApiReference/Data_Visualization_Widgets/dxChart/Configuration/series/aggregation/) description for information on how to configure aggregation for other use cases.
```

2020-09-17 13:10 UTC, pavel-2020 commented on JSDemos/Demos/Charts/PointsAggregationFinancialChart/description.md
> +In this demo, the **Chart** is bound to the [RangeSelector](/Documentation/ApiReference/Data_Visualization_Widgets/dxRangeSelector/) component. When you narrow down the selection range, the chart zoo
```suggestion
In this demo, the **Chart** is bound to the [RangeSelector](/Documentation/ApiReference/Data_Visualization_Widgets/dxRangeSelector/) component. The more the width of its selection range is, the bigger the graph scale and the degree of aggregation are, and vice versa. 
```

2020-09-17 13:10 UTC, pavel-2020 commented on JSDemos/Demos/Charts/PointsAggregationFinancialChart/description.md
> +Aggregation on zoom is only one use case for this feature. Refer to the [aggregation](/Documentation/ApiReference/Data_Visualization_Widgets/dxChart/Configuration/series/aggregation/) description for
```suggestion
Aggregation on zoom is only one use case for this feature. Refer to the [aggregation](/Documentation/ApiReference/Data_Visualization_Widgets/dxChart/Configuration/series/aggregation/) description on how to configure aggregation for other use cases.
```

2020-09-18 17:15 UTC, Abadzhev commented on JSDemos/Demos/Charts/PointsAggregationFinancialChart/description.md
> +In this demo, the **Chart** is bound to the [RangeSelector](/Documentation/ApiReference/Data_Visualization_Widgets/dxRangeSelector/) component. When you narrow down the selection range, the chart zoo
Just tightening up the other suggestion - it sound a bit better to me. 

```suggestion
In this demo, the **Chart** is bound to the [RangeSelector](/Documentation/ApiReference/Data_Visualization_Widgets/dxRangeSelector/) component. The wider you set the selection range, the higher aggregation degree the control uses, and vice versa.
```

2020-09-18 17:15 UTC, Abadzhev commented on JSDemos/Demos/Charts/PointsAggregationFinancialChart/description.md
> +Aggregation on zoom is only one use case for this feature. Refer to the [aggregation](/Documentation/ApiReference/Data_Visualization_Widgets/dxChart/Configuration/series/aggregation/) description for
I didn't want to repeat "cases" in two sentences. "One of many possible" sounds a bit better to me than "only one". The latter is somewhat vague - do we mean "one of many" or "the only one"?

```suggestion
Aggregation on zoom is one of many possible use cases for this feature. Refer to the [aggregation](/Documentation/ApiReference/Data_Visualization_Widgets/dxChart/Configuration/series/aggregation/) description for information on how to configure aggregation for other scenarios.
```

2020-09-22 18:30 UTC, albertov05 commented on JSDemos/Demos/Charts/PointsAggregationFinancialChart/description.md
> +In this demo, the **Chart** is bound to the [RangeSelector](/Documentation/ApiReference/Data_Visualization_Widgets/dxRangeSelector/) component. The wider you set the selection range, the higher aggre
In the demo, are you setting the "selection" to a wide range? For example, do you mean the following:

```suggestion
In this demo, the **Chart** is bound to the [RangeSelector](/Documentation/ApiReference/Data_Visualization_Widgets/dxRangeSelector/) component. If you set the selection to a wide range, the control will use a higher aggregation degree, and vice versa.
```

2020-09-22 18:38 UTC, albertov05 commented on JSDemos/Demos/Charts/PointsAggregationFinancialChart/description.md
> +Aggregation on zoom is one of many possible use cases for this feature. Refer to the [aggregation](/Documentation/ApiReference/Data_Visualization_Widgets/dxChart/Configuration/series/aggregation/) de
```suggestion
Aggregation on zoom is one of many possible use cases for this feature. For information on how to configure aggregation for other scenarios, refer to the following description: [aggregation](/Documentation/ApiReference/Data_Visualization_Widgets/dxChart/Configuration/series/aggregation/).
```

2020-09-23 08:33 UTC, RomanTsukanov approved these changes

2020-09-23 09:08 UTC, pavel-2020 approved these changes

2020-09-23 13:16 UTC, merged