DataGrid Editing: Add State Management demo
DevExpress/devextreme-demos pull request #146
Opened 2020-09-22 21:31 UTC by Alyar666

2020-09-23 06:44 UTC, jtoming830 requested changes

2020-09-23 06:44 UTC, jtoming830 commented on JSDemos/Demos/DataGrid/StateManagement/Angular/app/app.component.html
> +        [(changes)]="changes"
Not sure that we need adding two-way only for the `this.changes = []`

2020-09-23 06:44 UTC, jtoming830 commented on JSDemos/Demos/DataGrid/StateManagement/AngularJS/index.html
> +<!DOCTYPE html>
We don't add new demos on AngularJS since 19.2.

2020-09-23 06:44 UTC, jtoming830 commented on JSDemos/Demos/DataGrid/StateManagement/React/App.js
> +  data = data || {};
You can use `const sendRequest = (url, method = 'GET', data = {}) => {` instead of this.

2020-10-02 11:04 UTC, MikeVitik requested changes

2020-10-02 11:04 UTC, MikeVitik commented on JSDemos/Demos/DataGrid/StateManagement/Angular/app/app.service.ts
> +    updateOrders(change: any, data: any) {
I and @vconst suggest simplifying this and following function to
```
    updateOrders(change: any, data: any) {
        change.data = data;
        const orders = applyChanges(this.orders$.getValue(), [change], { keyExpr: "OrderID" });
        this.orders$.next(orders);
    }

    async loadAll() {
        const data = await this.http.get(`${this.url}/Orders?skip=700`, { withCredentials: true }).toPromise();
        this.orders$.next(data["data"]);
    }
```
@vconst suggest removing loadAll function at all and move their code into the getOrders function

2020-10-05 09:17 UTC, vconst requested changes

2020-10-05 09:17 UTC, vconst commented on JSDemos/Demos/DataGrid/StateManagement/Angular/app/app.component.ts
> +        this.service.loadAll().finally(() => { this.isLoading = false });
May be move loading to getOrders?

2020-10-05 09:17 UTC, vconst commented on JSDemos/Demos/DataGrid/StateManagement/React/App.js
> +    loadData();
The loadData method is not necessary here. You can call loadAll(dispatch) directly.
Also loadAll is strange name. I think it will be bettter to rename it to loadOrders or to loadData.

2020-10-05 09:17 UTC, vconst commented on JSDemos/Demos/DataGrid/StateManagement/React/App.js
> +        position={{ of: '#gridContainer' }}
Move it to constant because new instance of this object is created during internal state change.

2020-10-05 09:17 UTC, vconst commented on JSDemos/Demos/DataGrid/StateManagement/React/actions.js
> +export const loadAll = async (dispatch) => {
loadAll -> loadOrders or loadData

2020-10-09 13:53 UTC, vconst requested changes

2020-10-09 13:53 UTC, vconst commented on JSDemos/Demos/DataGrid/StateManagement/Angular/app/app.component.ts
> +        });
Add subscription disposing:

```
private ordersSubscription: Subscription;
...

this.ordersSubscription = this.orders$.subscribe(() => {
  this.isLoading = false;
});
...
ngOnDestroy() {
  this.ordersSubscription.unsubscribe();
}
```

2020-10-09 13:53 UTC, vconst commented on JSDemos/Demos/DataGrid/StateManagement/React/App.js
> +  const loadPanelPosition = { of: '#gridContainer' };
Move this constant outside component.

2020-10-09 13:53 UTC, vconst commented on JSDemos/menuMeta.json
> +            "Modules": "whatwg-fetch,vuex,devextreme-aspnet-data-nojquery",
Why is devextreme-aspnet-data-nojquery here?

2020-10-09 14:38 UTC, vconst requested changes

2020-10-09 14:38 UTC, vconst commented on JSDemos/Demos/DataGrid/StateManagement/Angular/app/app.component.ts
> +        e.cancel = true;
Move `e.cancel = true` to `if(change) {` block because save button should work if change does not exist.

2020-10-09 14:38 UTC, vconst commented on JSDemos/Demos/DataGrid/StateManagement/jQuery/index.js
> +            if (change) {
Move `e.cancel = true` to `if(change) {` block because save button should work if change does not exist.

2020-10-09 14:38 UTC, vconst commented on MVCDemos/Views/DataGrid/StateManagement.cshtml
> +        if (change) {
Move `e.cancel = true` to `if(change) {` block.

2020-10-09 14:38 UTC, vconst commented on NetCoreDemos/Views/DataGrid/StateManagement.cshtml
> +        if (change) {
Move `e.cancel = true` to `if(change) {` block.

2020-10-09 14:38 UTC, vconst commented on JSDemos/Demos/DataGrid/StateManagement/Angular/app/app.component.ts
> +        if(change) {
Move `e.cancel = true` to `if(change) {` block because save button should work if change does not exist.
Or add else where reset editing.editRowKey.

2020-10-12 07:48 UTC, vconst requested changes

2020-10-12 07:48 UTC, vconst commented on JSDemos/Demos/DataGrid/StateManagement/Angular/app/app.service.ts
> +        this.ordersSubscription = this.http.get(`${this.url}/Orders?skip=700`, { withCredentials: true }).subscribe((data) => {
it is not necessary to unsubscribe from http get observable.
See https://stackoverflow.com/questions/35042929/is-it-necessary-to-unsubscribe-from-observables-created-by-http-methods

2020-10-12 14:37 UTC, NickMitrokhin approved these changes, later dismissed

2020-10-12 16:08 UTC, vconst submitted a review, later dismissed

2020-10-12 16:22 UTC, jtoming830 approved these changes, later dismissed

2020-10-12 16:27 UTC, NickMitrokhin approved these changes, later dismissed

2020-10-13 07:45 UTC, MikeVitik submitted a review, later dismissed

2020-10-13 07:52 UTC, vconst approved these changes

2020-10-13 07:52 UTC, merged