Add editor labels demo
DevExpress/devextreme-demos pull request #1472
Opened 2021-10-21 11:52 UTC by groshenkovamarina

2021-10-21 12:41 UTC, babich-a commented on JSDemos/Demos/Common/LabelMode/Angular/app/app.component.html
> +    <div class="left">
display:inline-block and width: 49% can cause screenshots difference in visual tests. Flex will be the right solution.

2021-10-22 14:28 UTC, ksercs commented on JSDemos/Demos/Common/LabelMode/Angular/app/app.component.html
> +            {
let's use `<dxi-validation-rule>`

2021-10-22 14:28 UTC, ksercs commented on JSDemos/Demos/Common/LabelMode/Angular/app/app.component.ts
> +if (!/localhost/.test(document.location.host)) {
Is this a deliberate code?

2021-10-22 14:28 UTC, ksercs commented on JSDemos/Demos/Common/LabelMode/Angular/app/app.component.ts
> +    setTimeout(() => validationEngine.validateGroup());
why do we need it? I don't think it's a good idea to place such `setTimeout` in demo

2021-10-22 14:28 UTC, ksercs commented on JSDemos/Demos/Common/LabelMode/Angular/index.html
> +    <script src="https://unpkg.com/systemjs@0.21.3/dist/system.js"></script>
do we really need all these imports?

2021-10-22 14:28 UTC, ksercs commented on JSDemos/Demos/Common/LabelMode/Angular/index.html
> +    </script>
what is `config.js`? 
why do we need this catch?

2021-10-22 14:28 UTC, ksercs commented on JSDemos/Demos/Common/LabelMode/Angular/app/app.component.ts
> +import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
why do we use it?

2021-10-22 14:28 UTC, ksercs commented on JSDemos/Demos/Common/LabelMode/Vue/App.vue
> +              :validation-rules="[{ type: 'required' }]"
<DxRequiredRule>

2021-10-22 14:28 UTC, ksercs commented on JSDemos/Demos/Common/LabelMode/React/index.html
> +    <script type="text/javascript" src="config.js"></script>
.

2021-10-22 14:28 UTC, ksercs commented on JSDemos/Demos/Common/LabelMode/jQuery/index.js
> +  const place = $('#adress').dxTextBox({
aDDress.

let's fix it everywhere

2021-10-22 14:28 UTC, ksercs commented on JSDemos/Demos/Common/LabelMode/jQuery/index.html
> +    <script src="../../../../js/jquery.min.js"></script>
these all relative paths look like incorrect

2021-10-22 14:30 UTC, ksercs commented
What about new screenshot?

Why do we show new functionality exactly this way? So many repeating components, validation..

2021-10-22 15:02 UTC, DokaRus reviewed
What about AngularJS demo? We maintain it until the end of 2021

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/Angular/app/app.component.html
> +        value=""
Is it really necessary?

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/Angular/app/app.component.html
> +        placeholder="Type.."
```suggestion
        placeholder="Type..."
```

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/Angular/app/app.component.html
> +        label="Adress"
```suggestion
        label="Address"
```

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/Angular/app/app.component.html
> +          [validationRules]="[
Why not use `dxi-`?

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/Angular/app/app.component.html
> +        placeholder="Select.."
```suggestion
        placeholder="Select..."
```

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/Angular/app/app.component.html
> +          [validationRules]="[
Why not use `dxi-`?

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/Angular/app/app.component.html
> +      placeholder="Select.."
```suggestion
      placeholder="Select..."
```

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/Angular/app/app.component.html
> +        value=""
Is it really necessary?

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/Angular/app/app.component.html
> +        [validationRules]="[
`dxi`

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/Angular/app/app.component.html
> +          [validationRules]="[
`dxi`

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/Angular/app/app.component.html
> +        placeholder="Select.."
```suggestion
        placeholder="Select..."
```

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/Angular/app/app.component.html
> +          [validationRules]="[
`dxi`

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/Angular/app/app.component.html
> +      placeholder="Type.."
```suggestion
      placeholder="Type..."
```

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/React/App.js
> +                placeholder="Type.."
```suggestion
                placeholder="Type..."
```

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/React/App.js
> +                defaultValue=""
Is it really necessary?

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/React/App.js
> +                placeholder="Type.."
```suggestion
                placeholder="Type..."
```

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/React/App.js
> +                defaultValue=""
Is it really necessary?

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/React/App.js
> +                placeholder="Select.."
```suggestion
                placeholder="Select..."
```

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/React/App.js
> +                label="Adress"
```suggestion
                label="Address"
```

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/React/App.js
> +              placeholder="Select.."
```suggestion
              placeholder="Select..."
```

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/React/App.js
> +                defaultValue=""
Is it really necessary?

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/React/App.js
> +                defaultValue=""
Is it really necessary?

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/React/App.js
> +                placeholder="Select.."
```suggestion
                placeholder="Select..."
```

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/React/App.js
> +                defaultValue=""
Is it really necessary?

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/React/App.js
> +                placeholder="Select.."
```suggestion
                placeholder="Select..."
```

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/React/App.js
> +              placeholder="Type.."
```suggestion
              placeholder="Type..."
```

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/Vue/App.vue
> +            placeholder="Type.."
```suggestion
            placeholder="Type..."
```

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/Vue/App.vue
> +            value=""
Is it really necessary?

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/Vue/App.vue
> +            placeholder="Type.."
```suggestion
            placeholder="Type..."
```

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/Vue/App.vue
> +            label="Adress"
```suggestion
            label="Address"
```

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/Vue/App.vue
> +            placeholder="Select.."
```suggestion
            placeholder="Select..."
```

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/Vue/App.vue
> +            value=""
Is it really necessary?

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/Vue/App.vue
> +            placeholder="Select.."
```suggestion
            placeholder="Select..."
```

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/Vue/App.vue
> +              :validation-rules="[{ type: 'required' }]"
Use rule component

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/Vue/App.vue
> +              :validation-rules="[{ type: 'required' }]"
rule component

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/Vue/App.vue
> +              :validation-rules="[{ type: 'required' }]"
rule component

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/Vue/App.vue
> +          placeholder="Select.."
```suggestion
          placeholder="Select..."
```

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/Vue/App.vue
> +            :validation-rules="[{ type: 'required' }]"
rule component

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/Vue/App.vue
> +              value=""
Is it really necessary?

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/Vue/App.vue
> +            placeholder="Type.."
```suggestion
            placeholder="Type..."
```

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/Vue/App.vue
> +                :validation-rules="[{ type: 'required' }]"
rule component

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/Vue/App.vue
> +              placeholder="Select.."
```suggestion
              placeholder="Select..."
```

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/Vue/App.vue
> +                :validation-rules="[{ type: 'required' }]"
rule component

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/jQuery/index.html
> +            <div id="adress"></div>
```suggestion
            <div id="address"></div>
```

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/jQuery/index.js
> +    placeholder: 'Type..',
```suggestion
    placeholder: 'Type...',
```

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/jQuery/index.js
> +  const place = $('#adress').dxTextBox({
I see it just now...

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/jQuery/index.js
> +    value: '',
Is it really necessary?

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/jQuery/index.js
> +    placeholder: 'Type..',
```suggestion
    placeholder: 'Type...',
```

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/jQuery/index.js
> +    label: 'Adress',
```suggestion
    label: 'Address',
```

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/jQuery/index.js
> +    placeholder: 'Select..',
```suggestion
    placeholder: 'Select...',
```

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/jQuery/index.js
> +    placeholder: 'Select..',
```suggestion
    placeholder: 'Select...',
```

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/jQuery/index.js
> +    placeholder: 'Select..',
```suggestion
    placeholder: 'Select...',
```

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/jQuery/index.js
> +    placeholder: 'Select..',
```suggestion
    placeholder: 'Select...',
```

2021-10-22 15:02 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/jQuery/index.js
> +    placeholder: 'Type..',
```suggestion
    placeholder: 'Type...',
```

2021-10-22 15:02 UTC, DokaRus commented on MVCDemos/Views/Common/LabelMode.cshtml
> +                .Placeholder("Type..")
```suggestion
                .Placeholder("Type...")
```

2021-10-22 15:02 UTC, DokaRus commented on MVCDemos/Views/Common/LabelMode.cshtml
> +                .Value("")
Is it really necessary?

2021-10-22 15:02 UTC, DokaRus commented on MVCDemos/Views/Common/LabelMode.cshtml
> +                .Placeholder("Type..")
```suggestion
                .Placeholder("Type...")
```

2021-10-22 15:02 UTC, DokaRus commented on MVCDemos/Views/Common/LabelMode.cshtml
> +                .Label("Adress")
```suggestion
                .Label("Address")
```

2021-10-22 15:02 UTC, DokaRus commented on MVCDemos/Views/Common/LabelMode.cshtml
> +                .Placeholder("Select..")
```suggestion
                .Placeholder("Select...")
```

2021-10-22 15:02 UTC, DokaRus commented on MVCDemos/Views/Common/LabelMode.cshtml
> +                .Value("")
Is it really necessary?

2021-10-22 15:02 UTC, DokaRus commented on MVCDemos/Views/Common/LabelMode.cshtml
> +                .Placeholder("Select..")
```suggestion
                .Placeholder("Select...")
```

2021-10-22 15:02 UTC, DokaRus commented on MVCDemos/Views/Common/LabelMode.cshtml
> +            .Placeholder("Select..")
```suggestion
            .Placeholder("Select...")
```

2021-10-22 15:02 UTC, DokaRus commented on MVCDemos/Views/Common/LabelMode.cshtml
> +                .Value("")
Is it really necessary?

2021-10-22 15:02 UTC, DokaRus commented on MVCDemos/Views/Common/LabelMode.cshtml
> +                .Placeholder("Select..")
```suggestion
                .Placeholder("Select...")
```

2021-10-22 15:02 UTC, DokaRus commented on MVCDemos/Views/Common/LabelMode.cshtml
> +                .Placeholder("Type..")
```suggestion
                .Placeholder("Type...")
```

2021-10-22 15:02 UTC, DokaRus commented on NetCoreDemos/Views/Common/LabelMode.cshtml
> +                .Placeholder("Type..")
```suggestion
                .Placeholder("Type...")
```

2021-10-22 15:02 UTC, DokaRus commented on NetCoreDemos/Views/Common/LabelMode.cshtml
> +                .Value("")
Is it really necessary?

2021-10-22 15:02 UTC, DokaRus commented on NetCoreDemos/Views/Common/LabelMode.cshtml
> +                .Placeholder("Type..")
```suggestion
                .Placeholder("Type...")
```

2021-10-22 15:02 UTC, DokaRus commented on NetCoreDemos/Views/Common/LabelMode.cshtml
> +                .Label("Adress")
```suggestion
                .Label("Address")
```

2021-10-22 15:02 UTC, DokaRus commented on NetCoreDemos/Views/Common/LabelMode.cshtml
> +                .Placeholder("Select..")
```suggestion
                .Placeholder("Select...")
```

2021-10-22 15:02 UTC, DokaRus commented on NetCoreDemos/Views/Common/LabelMode.cshtml
> +                .Value("")
Is it really necessary?

2021-10-22 15:02 UTC, DokaRus commented on NetCoreDemos/Views/Common/LabelMode.cshtml
> +                .Placeholder("Select..")
```suggestion
                .Placeholder("Select...")
```

2021-10-22 15:02 UTC, DokaRus commented on NetCoreDemos/Views/Common/LabelMode.cshtml
> +            .Placeholder("Select..")
```suggestion
            .Placeholder("Select...")
```

2021-10-22 15:02 UTC, DokaRus commented on NetCoreDemos/Views/Common/LabelMode.cshtml
> +                .Value("")
Is it really necessary?

2021-10-22 15:02 UTC, DokaRus commented on NetCoreDemos/Views/Common/LabelMode.cshtml
> +                .Placeholder("Select..")
```suggestion
                .Placeholder("Select...")
```

2021-10-22 15:02 UTC, DokaRus commented on NetCoreDemos/Views/Common/LabelMode.cshtml
> +                .Placeholder("Type..")
```suggestion
                .Placeholder("Type...")
```

2021-10-22 15:32 UTC, babich-a commented on JSDemos/Demos/Common/LabelMode/Angular/index.html
> +    <script src="https://unpkg.com/systemjs@0.21.3/dist/system.js"></script>
It seems we import these files from node_modeules in others demos

2021-10-22 15:37 UTC, babich-a commented on JSDemos/Demos/Common/LabelMode/Angular/app/app.component.ts
> +if (!/localhost/.test(document.location.host)) {
yes, we use it in all demos to enable production mode on production (js.devexpress.com)

2021-10-22 15:37 UTC, babich-a commented on JSDemos/Demos/Common/LabelMode/Angular/index.html
> +    </script>
config.js is systemjs config

2021-10-22 15:47 UTC, babich-a requested changes

2021-10-22 15:47 UTC, babich-a commented on MVCDemos/DevExtreme.MVC.Demos.csproj
> +    <Content Include="Views\Shared\_DocumentDomain.cshtml" />
Wow, please remove this. It'll break the build

2021-10-27 13:38 UTC, ksercs commented on JSDemos/Demos/Common/LabelMode/Vue/App.vue
> +          :on-click="validateClick"
```suggestion
          @click="validateClick"
```

2021-10-27 13:43 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/Angular/app/app.component.ts
> +    setTimeout(() => validationEngine.validateGroup());
@groshenkovamarina Could you clarify?

2021-10-27 13:49 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/AngularJS/index.html
> +                    bindingOptions: { value: ' labelMode' }
```suggestion
                    bindingOptions: { value: 'labelMode' }
```

2021-10-27 13:49 UTC, DokaRus commented on JSDemos/Demos/Common/LabelMode/React/App.js
> +                defaultValue=""
Could you clarify?

2021-10-27 14:11 UTC, DokaRus submitted a review, later dismissed

2021-10-27 15:06 UTC, DokaRus approved these changes

2021-10-27 15:21 UTC, merged