Change the Export Multiple Grids demo description
DevExpress/devextreme-demos pull request #1781
Opened 2022-03-30 10:50 UTC by vladaskorohodova

2022-03-30 11:17 UTC, AnnaKondratova requested changes

2022-03-30 11:17 UTC, AnnaKondratova commented on JSDemos/Demos/DataGrid/PDFExportMultipleGrids/description.md
> +This demo shows two DataGrids in different tabs. The export system arranges these DataGrids on different pages of the PDF document.
```suggestion
This demo shows two DataGrids in different tabs. Click the "Export" button to export two grids and arrange them on different pages of the PDF document. 
```

2022-03-30 11:17 UTC, AnnaKondratova commented on JSDemos/Demos/DataGrid/PDFExportMultipleGrids/description.md
> +To implement this functionality, execute a <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then" target="_blank">chain of Promises</a>. Call the [exp
```suggestion
To implement this functionality, call the [exportDataGrid(options)](/Documentation/ApiReference/Common/Utils/pdfExporter/#exportDataGridoptions) methods in a <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then" target="_blank">chain of Promises</a> one after another. Use the **jsPDF**.<a href="https://raw.githack.com/parallax/jsPDF/master/docs/jsPDF.html#addPage" target="_blank">addPage()</a> method to add a page in the PDF document.
```

2022-03-30 11:17 UTC, AnnaKondratova commented on JSDemos/Demos/DataGrid/PDFExportMultipleGrids/description.md
> +You can use the [customizeCell](/Documentation/ApiReference/Common/Object_Structures/PdfExportDataGridProps/#customizeCell) function to customize cell appearance after export. In this demo, the **cus
```suggestion
You can use the [customizeCell](/Documentation/ApiReference/Common/Object_Structures/PdfExportDataGridProps/#customizeCell) function to customize cell appearance in the PDF document. In this demo, the **customizeCell** function highlights alternate (even) rows.
```

2022-03-30 11:22 UTC, vladaskorohodova commented on JSDemos/Demos/DataGrid/PDFExportMultipleGrids/description.md
> +This demo shows two DataGrids in different tabs. Click the "Export" button to export two grids and arrange them on different pages of the PDF document.
```suggestion
This demo shows two DataGrids in different tabs. Click the **Export multiple grids** button to export two grids and arrange them on different pages of the PDF document. 
```

2022-03-30 13:29 UTC, AnnaKondratova submitted a review, later dismissed

2022-03-30 21:55 UTC, albertov05 commented on JSDemos/Demos/DataGrid/PDFExportMultipleGrids/description.md
> +To implement this functionality, call the [exportDataGrid(options)](/Documentation/ApiReference/Common/Utils/pdfExporter/#exportDataGridoptions) methods in a <a href="https://developer.mozilla.org/en
```suggestion
To implement this functionality, call the [exportDataGrid(options)](/Documentation/ApiReference/Common/Utils/pdfExporter/#exportDataGridoptions) methods in a <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then" target="_blank">chain of Promises</a>, one after another. Use the **jsPDF**.<a href="https://raw.githack.com/parallax/jsPDF/master/docs/jsPDF.html#addPage" target="_blank">addPage()</a> method to add a page in the PDF document.
```

2022-03-31 05:16 UTC, EugeniyKiyashko approved these changes

2022-03-31 07:00 UTC, merged