v22.2 Add autoResizeEnabled for TextArea
DevExpress/devextreme-demos pull request #2187
Opened 2022-10-26 10:50 UTC by H-Frederick

Modified demos:
- jQuery
- Angular
- AngularJS
- React
- Vue
- ASP.NET Core
- ASP.NET MVC

2022-11-08 08:08 UTC, flagmanAndrew approved these changes, later dismissed

2022-11-08 09:05 UTC, Zedwag requested changes

2022-11-08 09:05 UTC, Zedwag commented on JSDemos/Demos/TextArea/Overview/Angular/app/app.component.ts
> +    this.autoResizeEnabled = e.value;
as far as we use 2way binding, there is no need to save `autoResizeEnabled ` value here, it should be alredy changed

2022-11-08 09:05 UTC, Zedwag commented on JSDemos/Demos/TextArea/Overview/Vue/App.vue
> +      this.value = e.value ? str.getContent().substring(0, 100) : str;
```suggestion
      this.value = e.value ? str.substring(0, 100) : str;
```

2022-11-08 09:05 UTC, Zedwag commented on JSDemos/Demos/TextArea/Overview/Vue/App.vue
> +      this.autoResizeEnabled = e.value;
just as in angular, there is no need to save value here

2022-11-08 09:05 UTC, Zedwag commented on JSDemos/Demos/TextArea/Overview/jQuery/index.js
> +      const str = data.value ? (exampleTextArea.option('value')).substring(0, 100) : longText;
```suggestion
      const str = data.value ? exampleTextArea.option('value').substring(0, 100) : longText;
```

2022-11-08 09:05 UTC, Zedwag commented on MVCDemos/Views/TextArea/Overview.cshtml
> +        exampleTextArea.option("value", data.value ? (exampleTextArea.option("value")).substring(0, 100) : null);
```suggestion
        exampleTextArea.option("value", data.value ? exampleTextArea.option("value").substring(0, 100) : null);
```

2022-11-08 09:05 UTC, Zedwag commented on NetCoreDemos/Views/TextArea/Overview.cshtml
> +        exampleTextArea.option("value", data.value ? (exampleTextArea.option("value")).substring(0, 100) : null);
```suggestion
        exampleTextArea.option("value", data.value ? exampleTextArea.option("value").substring(0, 100) : null);
```

2022-11-08 09:05 UTC, Zedwag commented on JSDemos/Demos/TextArea/Overview/AngularJS/index.html
> +        <div class="dx-field">
just for future, we ussually do not update angular js demos anymore

2022-12-15 13:38 UTC, Zedwag approved these changes

2022-12-15 14:16 UTC, flagmanAndrew approved these changes

2022-12-16 01:23 UTC, merged