vectorMap: add demos pan-visible and zoom-visible
DevExpress/devextreme-demos pull request #2229
Opened 2022-11-08 13:19 UTC by EvgeniiMorozovDevSoft

2022-11-08 14:51 UTC, alexanderPolosatov requested changes

2022-11-08 14:51 UTC, alexanderPolosatov commented on JSDemos/Demos/VectorMap/DynamicViewport/Angular/app/app.component.html
> +          (onValueChanged)="onValueChanged($event)"
onValueChanged is needed?

2022-11-08 14:51 UTC, alexanderPolosatov commented on JSDemos/Demos/VectorMap/DynamicViewport/Knockout/index.js
> +      onValueChanged: (data) => $('#vector-map').dxVectorMap('instance').option('controlBar.zoomVisible', data.value),
do not needed use this approach (with onValueChanged event using).

2022-11-08 14:51 UTC, alexanderPolosatov commented on JSDemos/Demos/VectorMap/DynamicViewport/jQuery/index.js
> +
extra line

2022-11-09 06:55 UTC, Krijovnick requested changes

2022-11-09 06:55 UTC, Krijovnick commented on JSDemos/Demos/VectorMap/DynamicViewport/Angular/app/app.component.html
> +    ></dxo-control-bar
delete unnecessary `>` and make <dxo-control-bar></dxo-control-bar> on one line

2022-11-09 06:55 UTC, Krijovnick commented on JSDemos/Demos/VectorMap/DynamicViewport/Angular/app/app.component.html
> +        <span>pan Visible</span>
Check text from correctors

2022-11-09 06:55 UTC, Krijovnick commented on JSDemos/Demos/VectorMap/DynamicViewport/Angular/app/app.component.html
> +        <span>zoom Visible</span>
Check text from correctors

2022-11-09 06:55 UTC, Krijovnick commented on JSDemos/Demos/VectorMap/DynamicViewport/Angular/app/app.component.html
> +        <dx-switch [value]="panVisible" #pan></dx-switch>
#pan - is this needed?

2022-11-09 06:55 UTC, Krijovnick commented on JSDemos/Demos/VectorMap/DynamicViewport/Angular/app/app.component.html
> +        <dx-switch [value]="zoomVisible" #zoom></dx-switch>
#zoom - is this needed?

2022-11-09 06:55 UTC, Krijovnick commented on JSDemos/Demos/VectorMap/DynamicViewport/AngularJS/index.html
> +              <span>pan Visible</span>
Check text

2022-11-09 06:55 UTC, Krijovnick commented on JSDemos/Demos/VectorMap/DynamicViewport/AngularJS/index.html
> +              <span>zoom Visible</span>
check text

2022-11-09 06:55 UTC, Krijovnick commented on JSDemos/Demos/VectorMap/DynamicViewport/Knockout/index.html
> +                            <span>pan Visible</span>
change span

2022-11-09 06:55 UTC, Krijovnick commented on JSDemos/Demos/VectorMap/DynamicViewport/Knockout/index.html
> +                            <span>zoom Visible</span>
change span

2022-11-09 06:55 UTC, Krijovnick commented on JSDemos/Demos/VectorMap/DynamicViewport/Knockout/index.html
> +                            <div data-bind="dxSwitch: chooseContinent"></div>
chooseContinent for panVisible?

2022-11-09 06:55 UTC, Krijovnick commented on JSDemos/Demos/VectorMap/DynamicViewport/Knockout/index.html
> +                            <div data-bind="dxSwitch: chooseContinent"></div>
chooseContinent for zoomVisible?

2022-11-09 06:55 UTC, Krijovnick commented on MVCDemos/Views/VectorMap/DynamicViewport.cshtml
> +               .ID("pan")
Is ID needed?

2022-11-09 06:55 UTC, Krijovnick commented on NetCoreDemos/Views/VectorMap/DynamicViewport.cshtml
> +﻿@model IEnumerable<DevExtreme.MVC.Demos.Models.ViewportCoordinate>
Why NetCore was changed to MVC?

2022-11-09 07:30 UTC, Krijovnick commented on JSDemos/Demos/VectorMap/DynamicViewport/React/App.js
> +                  onValueChanged={this.panVisibleChanged} />
In react should uses onValueChange option - https://js.devexpress.com/Documentation/Guide/React_Components/State_Management/?search=onValueChange=

2022-11-10 08:11 UTC, alexanderPolosatov approved these changes, later dismissed

2022-11-10 09:31 UTC, alexanderPolosatov approved these changes, later dismissed

2022-11-10 09:44 UTC, Krijovnick approved these changes, later dismissed

2022-11-10 10:49 UTC, Krijovnick approved these changes

2022-11-10 11:04 UTC, alexanderPolosatov approved these changes

2022-11-10 11:05 UTC, merged