Update FileUploader security for NetCore/Mvc
DevExpress/devextreme-demos pull request #2449
Opened 2023-02-14 15:08 UTC by OlegKipchatov

2023-02-14 15:19 UTC, Staziz requested changes

2023-02-14 15:19 UTC, Staziz commented on NetCoreDemos/Controllers/FileUploaderController.cs
> +        string[] ImageExtensions = { ".jpg", ".jpeg", ".gif", ".png" };
```suggestion
        string[] ImageExtensions = { ".JPG", ".JPEG", ".GIF", ".PNG" };
```

2023-02-14 16:49 UTC, mpreyskurantov commented on JSDemos/menuMeta.json
> +              "/Models/FileUploader/ChunkMetada.cs"
spelling
ChunkMetada.cs -> ChunkMetadata.cs

2023-02-14 16:50 UTC, mpreyskurantov requested changes

2023-02-14 16:50 UTC, mpreyskurantov commented on JSDemos/menuMeta.json
> +              "/Models/FileUploader/ChunkMetada.cs"
spelling
ChunkMetada.cs -> ChunkMetadata.cs

2023-02-15 07:54 UTC, mpreyskurantov submitted a review, later dismissed

2023-02-15 08:14 UTC, Staziz approved these changes, later dismissed

2023-02-15 10:11 UTC, mpreyskurantov approved these changes, later dismissed

2023-02-22 15:52 UTC, mpreyskurantov approved these changes

2023-02-22 16:12 UTC, merged