Gauges: update Overview demo with centerTemplate
DevExpress/devextreme-demos pull request #2474
Opened 2023-02-28 05:31 UTC by Krijovnick

2023-03-01 06:55 UTC, alexanderPolosatov requested changes

2023-03-01 06:55 UTC, alexanderPolosatov commented on JSDemos/Demos/Gauges/Overview/jQuery/index.js
> +      const content = $(`<svg>
we can not use this approach (creation elements by parsing string). see [this PR](https://github.com/DevExpress/devextreme-demos/commit/9f43bcb3cf73f90463a163b8b9304c521b9e0d08#diff-f5907593ee841b057984b53b6d0a9d69c8c20a241e8c751ec4da3a3e4fa258bdR20). 
this approach potential unsafe and we do not want to show this approach in demos

2023-03-01 06:55 UTC, alexanderPolosatov commented on JSDemos/Demos/Gauges/Overview/Knockout/index.js
> +        <circle cx="100" cy="100" r="55" stroke-width="2" stroke=${color} fill="transparent"></circle>
see comment below + do not use jQuery in no jQuery approaches

2023-03-01 13:00 UTC, alexanderPolosatov approved these changes

2023-03-01 21:01 UTC, ksercs approved these changes

2023-03-02 08:02 UTC, EugeniyKiyashko approved these changes

2023-03-06 10:05 UTC, merged