Convert FORMS AND MULTI-PURPOSE demos to functionality approach
DevExpress/devextreme-demos pull request #2727
Opened 2023-07-28 06:13 UTC by dxvladislavvolkov

2023-08-01 08:33 UTC, 16adianay commented on JSDemos/Demos/ButtonGroup/Overview/React/App.js
> +  const itemClick = React.useCallback((e) => {
if a function has no dependencies, it can be left outside a component

2023-08-01 08:36 UTC, 16adianay commented on JSDemos/Demos/Common/FormsAndMultiPurposeOverview/React/App.js
> +  const avatarRender = () => (
wrap this function in a hook or place outside a component

2023-08-01 08:41 UTC, 16adianay commented on JSDemos/Demos/FilterBuilder/WithDataGrid/React/App.js
> +  const dataSource = new DataSource({
place this variable outside a component

2023-08-01 08:48 UTC, 16adianay commented on JSDemos/Demos/Form/Validation/React/App.js
> +  function sendRequest(value) {
place this function outside a component

2023-08-01 08:53 UTC, 16adianay commented on JSDemos/Demos/RangeSelector/CustomFormatting/React/App.js
> +  const formatText = ({ valueText }) => `${valueText} mg/L`;
place this func outside a component

2023-08-01 08:53 UTC, 16adianay commented on JSDemos/Demos/RangeSelector/CustomizedChartOnBackground/React/App.js
> +  const format = ({ valueText }) => `${valueText} s`;
place this func outside a component

2023-08-01 08:55 UTC, 16adianay commented on JSDemos/Demos/RangeSelector/DiscreteScale/React/App.js
> +  function calculateTotalProduction(range = []) {
place this func outside a component

2023-08-01 09:00 UTC, 16adianay commented on JSDemos/Demos/Sortable/Customization/React/App.js
> +  const onDragStart = (e) => {
wrap this func in a hook

2023-08-01 09:02 UTC, 16adianay commented on JSDemos/Demos/Form/UpdateItemsDynamically/React/App.js
> +  const employee = service.getEmployee();
place outside or wrap in a hook

2023-08-04 06:34 UTC, alexanderPolosatov requested changes

2023-08-04 06:34 UTC, alexanderPolosatov commented on JSDemos/Demos/Form/GroupedFields/React/App.js
> +  const [employee] = React.useState(service.getEmployee());
employee not needed in the state

2023-08-04 06:34 UTC, alexanderPolosatov commented on JSDemos/Demos/Form/Validation/React/App.js
> +  const [passwordOptions] = React.useState({
passwordOptions and customer not needed in state

2023-08-07 08:02 UTC, alexanderPolosatov submitted a review, later dismissed

2023-08-07 10:35 UTC, ivanblinov2k17 approved these changes

2023-08-07 10:39 UTC, merged