Convert editor demos to ts
DevExpress/devextreme-demos pull request #2738
Opened 2023-08-01 08:48 UTC by const314

Wait for https://github.com/DevExpress/devextreme-demos/pull/2689 merge first, then rebase to 23_2 and merge

2023-08-10 06:35 UTC, ivanblinov2k17 approved these changes, later dismissed

2023-08-16 10:23 UTC, vladaskorohodova commented on README.md
> +### TS React infrastructure
```suggestion
### TS React Infrastructure
```

2023-08-16 10:23 UTC, vladaskorohodova commented on README.md
> +1. After you make any changes in react typescript sources you should run the following command:
```suggestion
1. After you make any changes in React TypeScript sources, run the following command:  
```

2023-08-16 10:23 UTC, vladaskorohodova commented on README.md
> +1. To ensure, that react javascript sources are always in sync, there is a workflow: "Check generated JS demos"
```suggestion
1. To ensure that React JavaScript sources are always in sync, there is a workflow: "Check generated JS demos"
```

In sync with what? And is this workflow on GitHub or where?

2023-08-16 15:19 UTC, ivanblinov2k17 commented on README.md
> +1. To ensure, that react javascript sources are always in sync, there is a workflow: "Check generated JS demos"
in sync with typescript sources)
now the sources are in typescript and js files are just transpiled ts
this workflow is on github actions lint -> check_generated_demos

2023-08-17 06:59 UTC, vladaskorohodova commented on README.md
> +1. To ensure that React JavaScript sources are always in sync, there is a workflow: "Check generated JS demos"
```suggestion
1. To ensure that React JavaScript and TypeScript sources are always in sync, the following GitHub action is used: "Check generated JS demos".
```

2023-08-17 08:19 UTC, OlegKipchatov requested changes

2023-08-17 08:19 UTC, OlegKipchatov commented on utils/ts-to-js-converter/converter.ts
> +import Os from 'os';
Maybe we can use uppercase for this?

2023-08-17 08:19 UTC, OlegKipchatov commented on JSDemos/Demos/Autocomplete/Overview/React/index.html
> +      System.import("./index.tsx");
Why we use tsx for ts, but not use jsx for js?
You sure that this can wroking in WG?

2023-08-17 08:19 UTC, OlegKipchatov commented on MVCDemos/Content/DemosStyles/Charts/PieWithAnnotations.css
> -﻿#pie {
I think you need to get rid of unnecessary changes

2023-08-17 10:37 UTC, dirk-pieterse approved these changes, later dismissed

2023-08-17 11:46 UTC, ivanblinov2k17 commented on utils/ts-to-js-converter/converter.ts
> +import Os from 'os';
You mean import _, {partial} from lodash?
It was the first way, that i tried to do, but i have the code, where i need the _ object to be a placeholder for first function argument

2023-08-17 12:00 UTC, ivanblinov2k17 commented on JSDemos/Demos/Autocomplete/Overview/React/index.html
> +      System.import("./index.tsx");
I haven't check this in WG, but Michael did and it worked. We can consult him after his return

2023-08-17 12:29 UTC, alexanderPolosatov submitted a review, later dismissed

2023-08-17 12:50 UTC, OlegKipchatov commented on utils/ts-to-js-converter/converter.ts
> +import Os from 'os';
No, I mean about 'Os'

2023-08-22 09:16 UTC, ivanblinov2k17 commented on tsconfig.json
> +    "utils/**/*.ts"
Add include paths for angular demos

2023-08-24 13:03 UTC, mpreyskurantov submitted a review, later dismissed

2023-08-24 13:47 UTC, mpreyskurantov submitted a review, later dismissed

2023-08-24 13:52 UTC, alexanderPolosatov submitted a review, later dismissed

2023-08-25 16:06 UTC, mpreyskurantov approved these changes

2023-08-25 16:07 UTC, merged