DRB Demo: add disableOutOfRangeSelection property demonstration
DevExpress/devextreme-demos pull request #2964
Opened 2023-11-02 11:56 UTC by AlexanderMoiseev

2023-11-02 15:09 UTC, Zedwag requested changes

2023-11-02 15:09 UTC, Zedwag commented on JSDemos/Demos/DateRangeBox/Overview/ReactJs/App.js
>            <DateRangeBox multiView={false} />
don't see new drb added in reactJs demo

2023-11-06 13:02 UTC, marker-dao approved these changes

2023-11-06 14:11 UTC, Zedwag approved these changes

2023-11-06 14:33 UTC, merged