Refactor types in Angular Demos p.3
DevExpress/devextreme-demos pull request #3074
Opened 2023-12-13 20:31 UTC by GoodDayForSurf

2023-12-27 13:42 UTC, dxvladislavvolkov requested changes

2023-12-27 13:42 UTC, dxvladislavvolkov commented on JSDemos/Demos/Scheduler/AllDayPanelMode/Angular/app/app.component.ts
> +import {DxRadioGroupTypes} from "devextreme-angular/ui/radio-group";
```suggestion
import { DxRadioGroupTypes } from "devextreme-angular/ui/radio-group";
```

2023-12-27 13:42 UTC, dxvladislavvolkov commented on JSDemos/Demos/Scheduler/CellTemplates/Angular/app/app.component.ts
> +import dxScheduler, {
In prev PRs you use dxComponent['instance']. Why do you use component from devextreme?

2023-12-27 13:42 UTC, dxvladislavvolkov commented on JSDemos/Demos/Scheduler/CellTemplates/Angular/app/app.component.ts
>    OptionChangedEvent, AppointmentFormOpeningEvent, AppointmentAddingEvent, AppointmentUpdatingEvent,
Why didn't you refactor the code and use types from devextreme?

2023-12-27 13:42 UTC, dxvladislavvolkov commented on JSDemos/Demos/Scheduler/CellTemplates/Angular/app/app.component.ts
> +import dxForm from 'devextreme/ui/form';
The same 
https://github.com/DevExpress/devextreme-demos/pull/3074/files#diff-488231ff0b06a9a0bde87310f0888999ac802e000f065eedda96effd409d65deR7

2023-12-27 13:42 UTC, dxvladislavvolkov commented on JSDemos/Demos/Scheduler/ContextMenuIntegration/Angular/app/app.component.ts
> +import { ItemClickEvent } from 'devextreme/ui/context_menu';
Why from devextreme?

2023-12-27 13:42 UTC, dxvladislavvolkov commented on JSDemos/Demos/ScrollView/Overview/Angular/app/app.component.ts
> +import {DxCheckBoxTypes} from "devextreme-angular/ui/check-box";
```suggestion
import { DxCheckBoxTypes } from "devextreme-angular/ui/check-box";
```

2023-12-27 13:42 UTC, dxvladislavvolkov commented on JSDemos/Demos/ScrollView/Overview/Angular/app/app.component.ts
> +import {DxSchedulerTypes} from "devextreme-angular/ui/scheduler";
```suggestion
import { DxSchedulerTypes } from "devextreme-angular/ui/scheduler";
```

2023-12-27 13:42 UTC, dxvladislavvolkov commented on JSDemos/Demos/ScrollView/Overview/Angular/app/app.component.ts
> +import {DxScrollViewTypes} from "devextreme-angular/ui/scroll-view";
```suggestion
import { DxScrollViewTypes } from "devextreme-angular/ui/scroll-view";
```

2023-12-27 13:42 UTC, dxvladislavvolkov commented on JSDemos/Demos/Sortable/Customization/Angular/app/app.component.ts
> +  dragDirections = ['both', 'vertical'];
Use DragDirection type

2023-12-27 13:42 UTC, dxvladislavvolkov commented on JSDemos/Demos/Sortable/Customization/Angular/app/app.component.ts
> +  dragDirection = 'both';
Use DragDirection type

2023-12-27 13:42 UTC, dxvladislavvolkov commented on JSDemos/Demos/Sortable/Customization/Angular/app/app.component.ts
> +  itemOrientation = 'vertical';
Use Orientation type from common

2023-12-27 13:42 UTC, dxvladislavvolkov commented on JSDemos/Demos/Tabs/Overview/Angular/app/app.component.ts
> +  orientations = ['horizontal', 'vertical'];
Use Orientation type

2023-12-27 13:42 UTC, dxvladislavvolkov commented on JSDemos/Demos/Tabs/Overview/Angular/app/app.component.ts
> +  stylingModes = ['primary', 'secondary'];
Do we have stylingModes type?

2023-12-27 13:42 UTC, dxvladislavvolkov commented on JSDemos/Demos/Tabs/Overview/Angular/app/app.component.ts
> +  iconPositions = ['top', 'start', 'end', 'bottom'];
Use position type from common

2023-12-27 13:42 UTC, dxvladislavvolkov commented on JSDemos/Demos/Tabs/Overview/Angular/app/app.component.ts
> +  orientation = this.orientations[0];
orientation type?

2023-12-27 13:42 UTC, dxvladislavvolkov commented on JSDemos/Demos/Toast/Stack/Angular/app/app.component.ts
> +import DevExpress from 'devextreme';
Remove it

2023-12-27 13:42 UTC, dxvladislavvolkov commented on JSDemos/Demos/Toolbar/Overview/Angular/app/app.component.ts
> +  selectBoxOptions: Record<string, unknown>;
it looks like you need to add types from devextreme-angular in this demo

2023-12-27 13:42 UTC, dxvladislavvolkov commented on JSDemos/Demos/TreeList/ColumnChooser/Angular/app/app.component.ts
> +  editorOptions = { placeholder: 'Search column' };
type?

2023-12-27 13:42 UTC, dxvladislavvolkov commented on JSDemos/Demos/TreeList/ColumnHeaderFilter/Angular/app/app.component.ts
> +  editorOptions = { placeholder: 'Search city or state' };
type?

2023-12-27 13:42 UTC, dxvladislavvolkov commented on JSDemos/Demos/TreeList/FilterPanel/Angular/app/app.component.ts
> +  filterValue = ['City', '=', 'Bentonville'];
do we have filter type?

2023-12-27 13:42 UTC, dxvladislavvolkov commented on JSDemos/Demos/TreeList/FormEditing/Angular/app/app.component.ts
>  import { DxTreeListModule } from 'devextreme-angular';
Move DxTreeListModule to next import

2023-12-27 13:42 UTC, dxvladislavvolkov commented on JSDemos/Demos/TreeView/FlatDataStructure/Angular/app/app.component.ts
>  import { DxTreeViewModule } from 'devextreme-angular';
Move DxTreeListModule to next import

2023-12-27 13:42 UTC, dxvladislavvolkov commented on JSDemos/Demos/TreeView/ItemSelectionAndCustomization/Angular/app/app.component.ts
> +import { DxTreeView } from 'devextreme-vue';
Vue ????

2023-12-27 13:42 UTC, dxvladislavvolkov commented on JSDemos/Demos/TreeView/ItemSelectionAndCustomization/Angular/app/app.component.ts
> +import { SingleOrMultiple, TreeViewCheckBoxMode } from 'devextreme/ui/tree_view';
Why do import from devextreme?

2023-12-27 13:42 UTC, dxvladislavvolkov commented on JSDemos/Demos/TreeView/LoadDataOnDemand/Angular/app/app.component.ts
> +import { DxTreeViewComponent, DxTreeViewModule } from 'devextreme-angular';
```suggestion
import { DxTreeViewComponent, DxTreeViewModule } from 'devextreme-angular/ui/tree-view';
```

2023-12-27 13:42 UTC, dxvladislavvolkov commented on JSDemos/Demos/Validation/Overview/Angular/app/app.component.ts
> +  passwordButton = {
Type?

2023-12-27 13:42 UTC, dxvladislavvolkov commented on JSDemos/Demos/Validation/Overview/Angular/app/app.component.ts
> +  confirmPasswordButton = {
Type?

2023-12-27 13:42 UTC, dxvladislavvolkov commented on JSDemos/Demos/VectorMap/Overview/Angular/app/app.component.ts
> +import { DxiLayerComponent } from 'devextreme-angular/ui/nested';
Why do you add the import

2023-12-27 13:42 UTC, dxvladislavvolkov commented on JSDemos/Demos/VectorMap/ZoomingAndCentering/Angular/app/app.component.ts
> +import {DxVectorMapTypes} from "devextreme-angular/ui/vector-map";
```suggestion
import { DxVectorMapTypes } from "devextreme-angular/ui/vector-map";
```

2024-02-05 06:11 UTC, mpreyskurantov submitted a review, later dismissed

2024-02-05 06:11 UTC, mpreyskurantov commented on JSDemos/Demos/Scheduler/Adaptability/Angular/app/app.component.ts
>  import { DxSpeedDialActionModule, DxSchedulerModule, DxSchedulerComponent } from 'devextreme-angular';
Component to ui

2024-02-05 06:11 UTC, mpreyskurantov commented on JSDemos/Demos/Scheduler/ContextMenuIntegration/Angular/app/app.component.ts
>  import { DxContextMenuModule, DxSchedulerModule, DxSchedulerComponent } from 'devextreme-angular';
Component to ui

2024-02-05 06:11 UTC, mpreyskurantov commented on JSDemos/Demos/Scheduler/CustomTemplates/Angular/app/app.component.ts
>  import { DxSchedulerModule, DxSchedulerComponent, DxTemplateModule } from 'devextreme-angular';
Component to ui

2024-02-05 06:11 UTC, mpreyskurantov commented on JSDemos/Demos/Scheduler/LimitAppointmentCountPerCell/Angular/app/app.component.ts
> +import { DxSchedulerModule, DxSchedulerComponent } from 'devextreme-angular';
ui

2024-02-05 06:11 UTC, mpreyskurantov commented on JSDemos/Demos/ScrollView/Overview/Angular/app/app.component.ts
>    DxScrollViewComponent,
Component to ui

2024-02-05 06:11 UTC, mpreyskurantov commented on JSDemos/Demos/Sortable/Customization/Angular/app/app.component.ts
> +import { DragDirection } from 'devextreme/common';
angular-common

2024-02-05 06:11 UTC, mpreyskurantov commented on JSDemos/Demos/Tabs/Overview/Angular/app/app.component.ts
>    DxTabsModule, DxSelectBoxModule, DxCheckBoxModule, DxTabsComponent,
Component to ui

2024-02-05 06:11 UTC, mpreyskurantov commented on JSDemos/Demos/TextBox/Overview/Angular/app/app.component.ts
> +import { DxTextBoxTypes } from 'devextreme-angular/ui/text-box';
Group module and types to ui

2024-02-05 06:11 UTC, mpreyskurantov commented on JSDemos/Demos/TreeList/BatchEditing/Angular/app/app.component.ts
> +import { DxTreeListTypes } from 'devextreme-angular/ui/tree-list';
Group module and types to ui

2024-02-05 06:11 UTC, mpreyskurantov commented on JSDemos/Demos/TreeList/CellEditing/Angular/app/app.component.ts
> +import { DxTreeListTypes } from 'devextreme-angular/ui/tree-list';
Group module and types to ui

2024-02-05 06:11 UTC, mpreyskurantov commented on JSDemos/Demos/TreeList/ColumnChooser/Angular/app/app.component.ts
> +import { DxTreeListTypes } from 'devextreme-angular/ui/tree-list';
Group module and types to ui

2024-02-05 06:11 UTC, mpreyskurantov commented on JSDemos/Demos/TreeList/CustomizeKeyboardNavigation/Angular/app/app.component.ts
> +import { DxTreeListTypes } from 'devextreme-angular/ui/tree-list';
Group module and types to ui

2024-02-05 06:11 UTC, mpreyskurantov commented on JSDemos/Demos/TreeList/FilterModes/Angular/app/app.component.ts
> +import { DxTreeListTypes } from 'devextreme-angular/ui/tree-list';
Group module and types to ui

2024-02-05 06:11 UTC, mpreyskurantov commented on JSDemos/Demos/TreeList/FocusedRow/Angular/app/app.component.ts
> +import { DxTreeListTypes } from 'devextreme-angular/ui/tree-list';
Group module and types to ui

2024-02-05 06:11 UTC, mpreyskurantov commented on JSDemos/Demos/TreeList/FormEditing/Angular/app/app.component.ts
> +import { DxTreeListTypes } from 'devextreme-angular/ui/tree-list';
Group module and types to ui

2024-02-05 06:11 UTC, mpreyskurantov commented on JSDemos/Demos/TreeList/LocalReordering/Angular/app/app.component.ts
> +import { DxTreeListTypes } from 'devextreme-angular/ui/tree-list';
Group module and types to ui

2024-02-05 06:11 UTC, mpreyskurantov commented on JSDemos/Demos/TreeList/MultipleRowSelection/Angular/app/app.component.ts
>  import { DxTreeListModule, DxCheckBoxModule, DxSelectBoxModule } from 'devextreme-angular';
Group module and types to ui

2024-02-05 06:11 UTC, mpreyskurantov commented on JSDemos/Demos/TreeList/PopupEditing/Angular/app/app.component.ts
>  import { DxTreeListModule } from 'devextreme-angular';
Group module and types to ui

2024-02-05 06:11 UTC, mpreyskurantov commented on JSDemos/Demos/TreeList/Resizing/Angular/app/app.component.ts
>  import { DxTreeListModule, DxSelectBoxModule } from 'devextreme-angular';
Group module and types to ui

2024-02-05 06:11 UTC, mpreyskurantov commented on JSDemos/Demos/TreeList/RowEditing/Angular/app/app.component.ts
>  import { DxTreeListModule } from 'devextreme-angular';
Group module and types to ui

2024-02-05 06:11 UTC, mpreyskurantov commented on JSDemos/Demos/TreeList/WebAPIService/Angular/app/app.component.ts
>  import { DxTreeListModule } from 'devextreme-angular';
Group module and types to ui

2024-02-05 06:11 UTC, mpreyskurantov commented on JSDemos/Demos/TreeView/ContextMenuIntegration/Angular/app/app.component.ts
>    DxTreeViewModule, DxTreeViewComponent, DxListModule, DxContextMenuModule, DxContextMenuComponent,
Group module, component and types to ui

2024-02-05 06:11 UTC, mpreyskurantov commented on JSDemos/Demos/TreeView/DragAndDropHierarchicalDataStructure/Angular/app/app.component.ts
>  import { DxTreeViewModule, DxTreeViewComponent, DxSortableModule } from 'devextreme-angular';
Group module and types to ui

2024-02-05 06:11 UTC, mpreyskurantov commented on JSDemos/Demos/TreeView/DragAndDropPlainDataStructure/Angular/app/app.component.ts
>  import { DxTreeViewModule, DxTreeViewComponent, DxSortableModule } from 'devextreme-angular';
Group module and types to ui

2024-02-05 06:11 UTC, mpreyskurantov commented on JSDemos/Demos/TreeView/HierarchicalDataStructure/Angular/app/app.component.ts
> +import { DxTreeViewTypes } from 'devextreme-angular/ui/tree-view';
Group module and types to ui

2024-02-05 06:11 UTC, mpreyskurantov commented on JSDemos/Demos/TreeView/ItemSelectionAndCustomization/Angular/app/app.component.ts
> +  DxListModule, DxTemplateModule, DxCheckBoxModule, DxSelectBoxModule,
Group module and types to ui

2024-02-05 06:11 UTC, mpreyskurantov commented on JSDemos/Demos/TreeView/LoadDataOnDemand/Angular/app/app.component.ts
> +import { DxTreeViewComponent, DxTreeViewModule } from 'devextreme-angular';
ui

2024-02-05 06:11 UTC, mpreyskurantov commented on JSDemos/Demos/TreeView/TreeViewWithSearchBar/Angular/app/app.component.ts
>  import { DxTreeViewModule, DxSelectBoxModule } from 'devextreme-angular';
Group module and types to ui

2024-02-05 06:11 UTC, mpreyskurantov commented on JSDemos/Demos/VectorMap/DynamicViewport/Angular/app/app.component.ts
>    DxVectorMapModule, DxSelectBoxModule, DxTextBoxModule, DxVectorMapComponent, DxSwitchModule,
Group module and types to ui

2024-02-07 07:21 UTC, dxvladislavvolkov approved these changes

2024-02-07 07:25 UTC, merged