Refactor types in Angular Demos p.2
DevExpress/devextreme-demos pull request #3075
Opened 2023-12-13 20:37 UTC by GoodDayForSurf

2023-12-20 05:54 UTC, dxvladislavvolkov commented on JSDemos/Demos/FilterBuilder/Customization/Angular/app/app.component.ts
> +import { DxFilterBuilder } from 'devextreme-vue';
Why do you use import from vue?

2023-12-20 05:54 UTC, dxvladislavvolkov commented on JSDemos/Demos/PivotGrid/ChartIntegration/Angular/app/app.component.html
> -    [allowSortingBySummary]="true"
Why did you remove the prop?

2023-12-21 21:51 UTC, GoodDayForSurf commented on JSDemos/Demos/PivotGrid/ChartIntegration/Angular/app/app.component.html
> -    [allowSortingBySummary]="true"
look upper, it's double

2023-12-27 13:09 UTC, dxvladislavvolkov requested changes

2023-12-27 13:09 UTC, dxvladislavvolkov commented on JSDemos/Demos/FileUploader/FileUploading/Angular/app/app.component.ts
> +} from 'devextreme-angular';
```suggestion
import { DxCheckBoxModule } from 'devextreme-angular/ui/check-box';
import { DxFileUploaderModule } from 'devextreme-angular/ui/file-uploader';
import { DxSelectBoxModule } from 'devextreme-angular/ui/select-box';
```

2023-12-27 13:09 UTC, dxvladislavvolkov commented on JSDemos/Demos/FilterBuilder/Customization/Angular/app/app.component.ts
> +import { DxListModule, DxButtonModule, DxTagBoxModule } from 'devextreme-angular';
```suggestion
import { DxListModule } from 'devextreme-angular/ui/list';
import { DxButtonModule } from 'devextreme-angular/ui/button';
import { DxTagBoxModule } from 'devextreme-angular/ui/tag-box';
```

2023-12-27 13:09 UTC, dxvladislavvolkov commented on JSDemos/Demos/FloatingActionButton/Overview/Angular/app/app.component.ts
> +import { DxSpeedDialActionModule } from 'devextreme-angular';
```suggestion
import { DxSpeedDialActionModule } from 'devextreme-angular/ui/speed-dial-action';
```

2023-12-27 13:09 UTC, dxvladislavvolkov commented on JSDemos/Demos/Form/ColumnsAdaptability/Angular/app/app.component.ts
> +import { DxFormModule } from 'devextreme-angular';
```suggestion
import { DxFormModule } from 'devextreme-angular/ui/form';
```

2023-12-27 13:09 UTC, dxvladislavvolkov commented on JSDemos/Demos/Form/Overview/Angular/app/app.component.ts
> +import { DxCheckBoxModule, DxSelectBoxModule, DxNumberBoxModule } from 'devextreme-angular';
```suggestion
import { DxCheckBoxModule } from 'devextreme-angular/ui/check-box';
import { DxSelectBoxModule } from 'devextreme-angular/ui/select-box';
import { DxNumberBoxModule } from 'devextreme-angular/ui/number-box';
```

2023-12-27 13:09 UTC, dxvladislavvolkov commented on JSDemos/Demos/Form/UpdateItemsDynamically/Angular/app/app.component.ts
> +import { DxFormModule } from 'devextreme-angular';
```suggestion
import { DxFormModule } from 'devextreme-angular/ui/form';
```

2023-12-27 13:09 UTC, dxvladislavvolkov commented on JSDemos/Demos/Gallery/Overview/Angular/app/app.component.ts
> +import { DxGalleryModule } from 'devextreme-angular';
```suggestion
import { DxGalleryModule } from 'devextreme-angular/ui/gallery';
```

2023-12-27 13:09 UTC, dxvladislavvolkov commented on JSDemos/Demos/Gantt/ChartAppearance/Angular/app/app.component.ts
> +import { DxCheckBoxModule, DxSelectBoxModule, DxDateBoxModule } from 'devextreme-angular';
```suggestion
import { DxCheckBoxModule } from 'devextreme-angular/ui/check-box';
import { DxSelectBoxModule } from 'devextreme-angular/ui/select-box';
import { DxDateBoxModule } from 'devextreme-angular/ui/date-box';
```

2023-12-27 13:09 UTC, dxvladislavvolkov commented on JSDemos/Demos/Gauges/VariableNumberOfSubvalueIndicators/Angular/app/app.component.ts
> +import { DxSelectBoxModule } from 'devextreme-angular';
```suggestion
import { DxSelectBoxModule } from 'devextreme-angular/ui/select-box';
```

2023-12-27 13:09 UTC, dxvladislavvolkov commented on JSDemos/Demos/HtmlEditor/ToolbarCustomization/Angular/app/app.component.ts
> +import { DxHtmlEditorModule, DxPopupModule } from 'devextreme-angular';
```suggestion
import { DxHtmlEditorModule } from 'devextreme-angular/ui/html-editor';
import { DxPopupModule } from 'devextreme-angular/ui/popup';
```

2023-12-27 13:09 UTC, dxvladislavvolkov commented on JSDemos/Demos/List/ItemDragging/Angular/app/app.component.ts
> +import { DxListComponent, DxListModule } from 'devextreme-angular';
```suggestion
import { DxListComponent, DxListModule } from 'devextreme-angular/ui/list';
```

2023-12-27 13:09 UTC, dxvladislavvolkov commented on JSDemos/Demos/List/ItemDragging/Angular/app/app.component.ts
> +type ListItemDragging = DxListComponent['itemDragging'];
I am not sure about this type. In this case I would prefer not to use types for handlers

2023-12-27 13:09 UTC, dxvladislavvolkov commented on JSDemos/Demos/Lookup/EventHandling/Angular/app/app.component.ts
> +import { DxSelectBoxModule } from 'devextreme-angular';
```suggestion
import { DxSelectBoxModule } from 'devextreme-angular/ui/select-box';
```

2023-12-27 13:09 UTC, dxvladislavvolkov commented on JSDemos/Demos/Map/Routes/Angular/app/app.component.ts
> +import { DxMapModule } from 'devextreme-angular';
```suggestion
import { DxMapModule } from 'devextreme-angular/ui/map';
```

2023-12-27 13:09 UTC, dxvladislavvolkov commented on JSDemos/Demos/Menu/Overview/Angular/app/app.component.ts
> +import { DxSelectBoxModule, DxCheckBoxModule } from 'devextreme-angular';
```suggestion
import { DxSelectBoxModule } from 'devextreme-angular/ui/select-box';
import { DxCheckBoxModule } from 'devextreme-angular/ui/check-box';
```

2023-12-27 13:09 UTC, dxvladislavvolkov commented on JSDemos/Demos/PivotGrid/ExcelJsHeaderAndFooter/Angular/app/app.component.ts
> +import { DxCheckBoxModule } from 'devextreme-angular';
```suggestion
import { DxCheckBoxModule } from 'devextreme-angular/ui/check-box';
```

2023-12-27 13:09 UTC, dxvladislavvolkov commented on JSDemos/Demos/PivotGrid/FieldPanel/Angular/app/app.component.ts
> +import { DxCheckBoxModule } from 'devextreme-angular';
```suggestion
import { DxCheckBoxModule } from 'devextreme-angular/ui/check-box';
```

2023-12-27 13:09 UTC, dxvladislavvolkov commented on JSDemos/Demos/PivotGrid/IntegratedFieldChooser/Angular/app/app.component.ts
> +import { DxSelectBoxModule } from 'devextreme-angular';
```suggestion
import { DxSelectBoxModule } from 'devextreme-angular/ui/select-box';
```

2023-12-27 13:09 UTC, dxvladislavvolkov commented on JSDemos/Demos/PivotGrid/StatePersistence/Angular/app/app.component.ts
> +import { DxButtonModule } from 'devextreme-angular';
```suggestion
import { DxButtonModule } from 'devextreme-angular/ui/button';
```

2023-12-27 13:09 UTC, dxvladislavvolkov commented on JSDemos/Demos/RangeSelector/UseRangeSelectionForCalculation/Angular/app/app.component.ts
> +import { DxSelectBoxModule } from 'devextreme-angular';
```suggestion
import { DxSelectBoxModule } from 'devextreme-angular/ui/select-box';
```

2023-12-27 13:09 UTC, dxvladislavvolkov commented on JSDemos/Demos/RangeSelector/UseRangeSelectionForFiltering/Angular/app/app.component.ts
> +import { DxDataGridModule } from 'devextreme-angular';
```suggestion
import { DxDataGridModule } from 'devextreme-angular/ui/data-grid';
```

2024-02-01 20:36 UTC, mpreyskurantov approved these changes, later dismissed

2024-02-01 20:36 UTC, mpreyskurantov commented on JSDemos/Demos/FilterBuilder/Customization/Angular/app/app.component.ts
> +import { DxTagBoxModule } from 'devextreme-angular/ui/tag-box';
Revert. Only Modules from root.

2024-02-01 20:36 UTC, mpreyskurantov commented on JSDemos/Demos/FloatingActionButton/Overview/Angular/app/app.component.ts
> +import { DxSpeedDialActionModule } from 'devextreme-angular/ui/speed-dial-action';
Module from root.

2024-02-01 20:36 UTC, mpreyskurantov commented on JSDemos/Demos/Form/ColumnsAdaptability/Angular/app/app.component.ts
> +import { DxFormModule } from 'devextreme-angular/ui/form';
root

2024-02-01 20:36 UTC, mpreyskurantov commented on JSDemos/Demos/Form/Overview/Angular/app/app.component.ts
> +import { DxNumberBoxModule } from 'devextreme-angular/ui/number-box';
Revert

2024-02-01 20:36 UTC, mpreyskurantov commented on JSDemos/Demos/Form/UpdateItemsDynamically/Angular/app/app.component.ts
> +import { DxFormModule } from 'devextreme-angular/ui/form';
Revert

2024-02-01 20:36 UTC, mpreyskurantov commented on JSDemos/Demos/Gallery/Overview/Angular/app/app.component.ts
> +import { DxGalleryModule } from 'devextreme-angular/ui/gallery';
root

2024-02-01 20:36 UTC, mpreyskurantov commented on JSDemos/Demos/List/ItemDragging/Angular/app/app.component.ts
> +import { DxListModule } from 'devextreme-angular/ui/list';
Revert

2024-02-01 20:36 UTC, mpreyskurantov commented on JSDemos/Demos/List/ListSelection/Angular/app/app.component.ts
> +import { SingleMultipleAllOrNone } from 'devextreme/common';
devextreme-angular/common

2024-02-01 20:36 UTC, mpreyskurantov commented on JSDemos/Demos/PivotGrid/FieldPanel/Angular/app/app.component.ts
> +import { DxCheckBoxModule } from 'devextreme-angular/ui/check-box';
root

2024-02-01 20:36 UTC, mpreyskurantov commented on JSDemos/Demos/PivotGrid/IntegratedFieldChooser/Angular/app/app.component.ts
> +import { DxSelectBoxModule } from 'devextreme-angular/ui/select-box';
root

2024-02-01 20:36 UTC, mpreyskurantov commented on JSDemos/Demos/PivotGrid/StatePersistence/Angular/app/app.component.ts
> +import { DxButtonModule } from 'devextreme-angular/ui/button';
root

2024-02-01 20:36 UTC, mpreyskurantov commented on JSDemos/Demos/RangeSelector/UseRangeSelectionForCalculation/Angular/app/app.component.ts
> +import { DxSelectBoxModule } from 'devextreme-angular/ui/select-box';
root

2024-02-01 20:36 UTC, mpreyskurantov commented on JSDemos/Demos/RangeSelector/UseRangeSelectionForFiltering/Angular/app/app.component.ts
> +import { DxDataGridModule } from 'devextreme-angular/ui/data-grid';
root

2024-02-06 13:19 UTC, dxvladislavvolkov approved these changes

2024-02-06 13:47 UTC, merged