Refactor types in Angular Demos p.1
DevExpress/devextreme-demos pull request #3076
Opened 2023-12-13 20:41 UTC by GoodDayForSurf

2023-12-20 05:40 UTC, dxvladislavvolkov commented on JSDemos/Demos/Autocomplete/Overview/Angular/app/app.component.ts
> +import { LoadOptions } from 'devextreme/data';
Get rid of type from devextreme package

2023-12-20 05:40 UTC, dxvladislavvolkov commented on JSDemos/Demos/Charts/LoadDataOnDemand/Angular/app/app.component.html
> -    [visualRangeUpdateMode]="keep"
Why did you remove the prop?

2023-12-20 05:40 UTC, dxvladislavvolkov commented on JSDemos/Demos/Charts/LoadDataOnDemand/Angular/app/app.component.ts
> +import { VisualRange } from 'devextreme/common/charts';
import type from 'devextreme-angular/common/charts'

2023-12-20 05:40 UTC, dxvladislavvolkov commented on JSDemos/Demos/Diagram/ItemSelection/Angular/app/app.component.ts
> +import { DxDiagramModule } from 'devextreme-angular';
Move diagram import to 10 line

2023-12-20 05:40 UTC, dxvladislavvolkov commented on JSDemos/Demos/DropDownButton/Overview/Angular/app/app.component.ts
> +  dropDownButton: DxDropDownButtonComponent['instance'];
I think we need to discuss the solution with techlead

2023-12-20 05:40 UTC, dxvladislavvolkov commented on JSDemos/Demos/DropDownButton/Overview/Angular/app/app.component.ts
> +  dropDownButton: DxDropDownButtonComponent['instance'];
@IlyaKhD

2023-12-27 12:21 UTC, dxvladislavvolkov requested changes

2023-12-27 12:21 UTC, dxvladislavvolkov commented on JSDemos/Demos/Charts/Colorization/Angular/app/app.component.ts
> +  options: ColorizationOption [ 'options' ];
Remove space after ColorizationOption

2023-12-27 12:21 UTC, dxvladislavvolkov commented on JSDemos/Demos/FileManager/Overview/Angular/app/app.component.ts
> +import { DxPopupModule } from 'devextreme-angular';
```suggestion
import { DxPopupModule } from 'devextreme-angular/ui/popup';
```

2023-12-27 12:21 UTC, dxvladislavvolkov commented on JSDemos/Demos/DropDownButton/Overview/Angular/app/app.component.ts
> +import { DxToolbarModule } from 'devextreme-angular';
```suggestion
import { DxToolbarModule } from 'devextreme-angular/ui/toolbar';
```

2023-12-27 12:21 UTC, dxvladislavvolkov commented on JSDemos/Demos/DropDownBox/SingleSelection/Angular/app/app.component.ts
> +import { DxDataGridModule } from 'devextreme-angular';
```suggestion
import { DxDataGridModule } from 'devextreme-angular/ui/data-grid';
```

2023-12-27 12:21 UTC, dxvladislavvolkov commented on JSDemos/Demos/DropDownBox/MultipleSelection/Angular/app/app.component.ts
> +import { DxDropDownBoxModule, DxDataGridModule } from 'devextreme-angular';
```suggestion
import { DxDropDownBoxModule } from 'devextreme-angular/ui/drop-down-box';
import { DxDataGridModule } from 'devextreme-angular/ui/data-grid';
```

2023-12-27 12:21 UTC, dxvladislavvolkov commented on JSDemos/Demos/Drawer/TopOrBottomPosition/Angular/app/app.component.ts
> +import { DxListModule, DxRadioGroupModule, DxToolbarModule } from 'devextreme-angular';
```suggestion
import { DxListModule } from 'devextreme-angular/ui/list';
import { DxRadioGroupModule } from 'devextreme-angular/ui/radio-group';
import { DxToolbarModule } from 'devextreme-angular/ui/toolbar';
```

2023-12-27 12:21 UTC, dxvladislavvolkov commented on JSDemos/Demos/Drawer/LeftOrRightPosition/Angular/app/app.component.ts
> +import { DxListModule, DxRadioGroupModule, DxToolbarModule } from 'devextreme-angular';
```suggestion
import { DxListModule } from 'devextreme-angular/ui/list';
import { DxRadioGroupModule } from 'devextreme-angular/ui/radio-group';
import { DxToolbarModule } from 'devextreme-angular/ui/toolbar';
```

2023-12-27 12:21 UTC, dxvladislavvolkov commented on JSDemos/Demos/Diagram/NodesArrayPlainStructure/Angular/app/app.component.ts
> +import { DxDiagramModule } from 'devextreme-angular';
```suggestion
import { DxDiagramModule } from 'devextreme-angular/ui/diagram';
```

2023-12-27 12:21 UTC, dxvladislavvolkov commented on JSDemos/Demos/Diagram/ItemSelection/Angular/app/app.component.ts
> +  selectedItems: DxDiagramTypes.SelectionChangedEvent['items'];
Use DxDiagramTypes.Item type

2023-12-27 12:21 UTC, dxvladislavvolkov commented on JSDemos/Demos/ContextMenu/Templates/Angular/app/app.component.ts
> +import { DxTemplateModule } from 'devextreme-angular';
```suggestion
```

2023-12-27 12:21 UTC, dxvladislavvolkov commented on JSDemos/Demos/Common/EditorAppearanceVariants/Angular/app/app.component.ts
> +  labelMode: DxTextBoxTypes.Properties['labelMode'] = 'static';
Use LabelMode type from 'devextreme-angular/common'

2023-12-27 12:21 UTC, dxvladislavvolkov commented on JSDemos/Demos/Common/EditorAppearanceVariants/Angular/app/app.component.ts
> +  stylingMode: DxTextBoxTypes.Properties['stylingMode'] = 'outlined';
Use StylingMode type from 'devextreme-angular/common'

2023-12-27 12:21 UTC, dxvladislavvolkov commented on JSDemos/Demos/Common/CustomTextEditorButtons/Angular/app/app.component.ts
> +  passwordMode: DxTextBoxTypes.Properties['mode'] = 'password';
Use Mode type from 'devextreme-angular/common'

2023-12-27 12:21 UTC, dxvladislavvolkov commented on JSDemos/Demos/Common/CustomTextEditorButtons/Angular/app/app.component.ts
> +import { DxNumberBoxModule, DxDateBoxModule } from 'devextreme-angular';
```suggestion
import { DxNumberBoxModule } from 'devextreme-angular/ui/number-box';
import { DxDateBoxModule } from 'devextreme-angular/ui/date-box';
```

2023-12-27 12:21 UTC, dxvladislavvolkov commented on JSDemos/Demos/Charts/ZoomingAndScrollingAPI/Angular/app/app.component.ts
> +import { DxRangeSelectorModule } from 'devextreme-angular';
```suggestion
import { DxRangeSelectorModule } from 'devextreme-angular/ui/range-selector';
```

2023-12-27 12:21 UTC, dxvladislavvolkov commented on JSDemos/Demos/Charts/WindRose/Angular/app/app.component.ts
> +import { DxSelectBoxModule } from 'devextreme-angular';
```suggestion
import { DxSelectBoxModule } from 'devextreme-angular/ui/select-box';
```

2023-12-27 12:21 UTC, dxvladislavvolkov commented on JSDemos/Demos/Charts/PolarChartZoomingAndScrollingAPI/Angular/app/app.component.ts
> +import { DxRangeSelectorModule } from 'devextreme-angular';
```suggestion
import { DxRangeSelectorModule } from 'devextreme-angular/ui/range-selector';
```

2023-12-27 12:21 UTC, dxvladislavvolkov commented on JSDemos/Demos/Charts/PointsAggregationFinancialChart/Angular/app/app.component.ts
> +import { DxRangeSelectorModule } from 'devextreme-angular';
```suggestion
import { DxRangeSelectorModule } from 'devextreme-angular/ui/range-selector';
```

2023-12-27 12:21 UTC, dxvladislavvolkov commented on JSDemos/Demos/Charts/Palette/Angular/app/app.service.ts
> +  getPaletteCollection(): DxChartTypes.Properties['palette'][] {
Use Palette type from 'devextreme-angular/common/charts'

2023-12-27 12:21 UTC, dxvladislavvolkov commented on JSDemos/Demos/Charts/Palette/Angular/app/app.service.ts
> +  getPaletteExtensionModes(): DxChartTypes.Properties['paletteExtensionMode'][] {
Use PaletteExtensionMode type from 'devextreme-angular/common/charts'

2023-12-27 12:21 UTC, dxvladislavvolkov commented on JSDemos/Demos/Charts/Palette/Angular/app/app.component.ts
> +  palette: DxPieChartTypes.Properties['palette'];
Use Palette type from 'devextreme-angular/common/charts'

2023-12-27 12:21 UTC, dxvladislavvolkov commented on JSDemos/Demos/Charts/Palette/Angular/app/app.component.ts
> +  paletteExtensionModes: DxPieChartTypes.Properties['paletteExtensionMode'][];
Use PaletteExtensionMode type from 'devextreme-angular/common/charts'

2023-12-27 12:21 UTC, dxvladislavvolkov commented on JSDemos/Demos/Charts/Palette/Angular/app/app.component.ts
> +import { DxSelectBoxModule } from 'devextreme-angular';
```suggestion
import { DxSelectBoxModule } from 'devextreme-angular/ui/select-box';
```

2023-12-27 12:21 UTC, dxvladislavvolkov commented on JSDemos/Demos/Charts/PointsAggregationFinancialChart/Angular/app/app.component.ts
> +  visualRange: DxChartTypes.ArgumentAxis['visualRange'] = {};
Use VisualRange type from 'devextreme-angular/common/charts'

2023-12-27 12:21 UTC, dxvladislavvolkov commented on JSDemos/Demos/Charts/PointsAggregationFinancialChart/Angular/app/app.component.ts
> +  visualRange: DxChartTypes.ArgumentAxis['visualRange'] = {};
Fix it in all changes

2023-12-27 12:21 UTC, dxvladislavvolkov commented on JSDemos/Demos/Charts/Palette/Angular/app/app.component.ts
> +  paletteExtensionMode: DxPieChartTypes.Properties['paletteExtensionMode'] = 'blend';
Use PaletteExtensionMode type from 'devextreme-angular/common/charts'

2023-12-27 12:21 UTC, dxvladislavvolkov commented on JSDemos/Demos/Charts/ExportAndPrintingAPI/Angular/app/app.component.ts
> +import { DxButtonModule } from 'devextreme-angular';
```suggestion
import { DxButtonModule } from 'devextreme-angular/ui/button';
```

2023-12-27 12:21 UTC, dxvladislavvolkov commented on JSDemos/Demos/Charts/DiscreteAxisZoomingAndScrolling/Angular/app/app.component.ts
> +import { DxRangeSelectorModule } from 'devextreme-angular';
```suggestion
import { DxRangeSelectorModule } from 'devextreme-angular/ui/range-selector';
```

2023-12-27 12:21 UTC, dxvladislavvolkov commented on JSDemos/Demos/Charts/Colorization/Angular/app/app.component.ts
> +import { DxSelectBoxModule } from 'devextreme-angular';
```suggestion
import { DxSelectBoxModule } from 'devextreme-angular/ui/select-box';
```

2023-12-27 12:21 UTC, dxvladislavvolkov commented on JSDemos/Demos/Calendar/MultipleSelection/Angular/app/app.component.ts
> +import { DxSelectBoxModule, DxCheckBoxModule, DxButtonModule } from 'devextreme-angular';
```suggestion
import { DxSelectBoxModule } from 'devextreme-angular/ui/select-box';
import { DxCheckBoxModule } from 'devextreme-angular/ui/check-box';
import { DxButtonModule } from 'devextreme-angular/ui/button';
```

2024-01-30 10:12 UTC, ivanblinov2k17 commented on JSDemos/Demos/Charts/APIDisplayATooltip/Angular/app/app.component.ts
> +    this.selectedRegion = point.data.region;
Seems like this change isn't straight connected to type rework, did you check the demo behaviour?

2024-01-30 10:17 UTC, ivanblinov2k17 commented on JSDemos/Demos/Charts/BiDirectionalBarChart/Angular/app/app.component.ts
> +  customizeLabel: DxChartTypes.ValueAxisLabel['customizeText'] = ({ value }) => `${Math.abs(value as number)}%`;
Maybe use same syntax as in function above instead of long type + type casting?

2024-01-30 10:26 UTC, ivanblinov2k17 commented on JSDemos/Demos/Charts/CustomAnnotations/Angular/app/app.component.ts
> -  pipe: any = new DecimalPipe('en-US');
Was it an unused variable?

2024-01-30 14:02 UTC, mpreyskurantov requested changes

2024-01-30 14:02 UTC, mpreyskurantov commented on JSDemos/Demos/Autocomplete/Overview/Angular/app/app.component.ts
>  import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
Modules imports groups are ok, but may be to sort both angular's and our devextreme data imports alphabetically:

`import { HttpClient, HttpClientModule, HttpParams } from '@angular/common/http';`
`import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';`

and

`import CustomStore from 'devextreme/data/custom_store';`
`import ODataStore from 'devextreme/data/odata/store';`

2024-01-30 14:02 UTC, mpreyskurantov commented on JSDemos/Demos/Calendar/MultipleSelection/Angular/app/app.component.ts
> +import { DxSelectBoxModule } from 'devextreme-angular/ui/select-box';
Group Modules imports from root (like before change), sort inside.
Sort imports from ui (button, checkbox, etc.).

2024-01-30 14:02 UTC, mpreyskurantov commented on JSDemos/Demos/Calendar/Overview/Angular/app/app.component.ts
> +  DxSelectBoxModule, DxCheckBoxModule, DxDateBoxModule, DxTemplateModule,
Sort inside?  DxSelectBoxModul at the end.

2024-01-30 14:02 UTC, mpreyskurantov commented on JSDemos/Demos/Charts/Area/Angular/app/app.component.ts
> +import { DxChartTypes } from 'devextreme-angular/ui/chart';
Group DxChartModule with DxChartTypes

2024-01-30 14:02 UTC, mpreyskurantov commented on JSDemos/Demos/Charts/Colorization/Angular/app/app.component.ts
> +import { DxSelectBoxModule } from 'devextreme-angular/ui/select-box';
Import from root.

2024-01-30 14:02 UTC, mpreyskurantov commented on JSDemos/Demos/Charts/DiscreteAxisZoomingAndScrolling/Angular/app/app.component.ts
> +import { DxRangeSelectorModule } from 'devextreme-angular/ui/range-selector';
Import from root.

2024-01-30 14:02 UTC, mpreyskurantov commented on JSDemos/Demos/Charts/ExportAndPrintingAPI/Angular/app/app.component.ts
> +import { DxButtonModule } from 'devextreme-angular/ui/button';
Import from root.

2024-01-30 14:02 UTC, mpreyskurantov commented on JSDemos/Demos/Charts/LoadDataOnDemand/Angular/app/app.component.ts
> +import { VisualRange } from 'devextreme-angular/common/charts';
Respect)

2024-01-30 14:02 UTC, mpreyskurantov commented on JSDemos/Demos/Charts/Palette/Angular/app/app.component.ts
> +import { DxPieChartModule } from 'devextreme-angular/ui/pie-chart';
Import from root (group with another).

2024-01-30 14:02 UTC, mpreyskurantov commented on JSDemos/Demos/Charts/PointsAggregation/Angular/app/app.component.ts
>  import { DxChartModule, DxSelectBoxModule, DxCheckBoxModule } from 'devextreme-angular';
Was not changed. Looks good so far, but may be to sort inside.

2024-01-30 14:02 UTC, mpreyskurantov commented on JSDemos/Demos/Charts/SignalRService/Angular/app/app.component.ts
> +import { DxChartModule, DxChartComponent, DxChartTypes } from 'devextreme-angular/ui/chart';
Respect;) We did not discuss this, but looks great: module, component, ..., re-exported types

2024-01-30 14:02 UTC, mpreyskurantov commented on JSDemos/Demos/Charts/WindRose/Angular/app/app.component.ts
> +import { DxSelectBoxModule } from 'devextreme-angular';
Sort. Root is first.?

2024-01-30 14:02 UTC, mpreyskurantov commented on JSDemos/Demos/Common/CustomTextEditorButtons/Angular/app/app.component.ts
> +import { DxButtonTypes } from 'devextreme-angular/ui/button';
Move to root.

2024-01-30 14:02 UTC, mpreyskurantov commented on JSDemos/Demos/ContextMenu/Basics/Angular/app/app.component.ts
> +import { DxContextMenuModule, DxContextMenuTypes } from 'devextreme-angular/ui/context-menu';
Move before notify.

2024-01-30 14:02 UTC, mpreyskurantov commented on JSDemos/Demos/ContextMenu/Templates/Angular/app/app.component.ts
> +import { DxContextMenuModule, DxContextMenuTypes } from 'devextreme-angular/ui/context-menu';
Move before notify.

2024-01-30 14:02 UTC, mpreyskurantov commented on JSDemos/Demos/Diagram/OperationRestrictions/Angular/app/app.component.ts
>  import notify from 'devextreme/ui/notify';
After devextreme-angular

2024-01-30 14:02 UTC, mpreyskurantov commented on JSDemos/Demos/DropDownBox/MultipleSelection/Angular/app/app.component.ts
> +import { DxDropDownBoxModule } from 'devextreme-angular/ui/drop-down-box';
Group to root. Keep devextreme-angular before notify.

2024-01-30 14:02 UTC, mpreyskurantov commented on JSDemos/Demos/DropDownBox/SingleSelection/Angular/app/app.component.ts
> +import { DxDataGridModule } from 'devextreme-angular/ui/data-grid';
Move to root.

2024-01-30 14:02 UTC, mpreyskurantov commented on JSDemos/Demos/DropDownButton/Overview/Angular/app/app.component.ts
> +import { DxToolbarModule } from 'devextreme-angular/ui/toolbar';
Move to root.

2024-01-30 14:02 UTC, mpreyskurantov commented on JSDemos/Demos/FileManager/Overview/Angular/app/app.component.ts
> +import { DxPopupModule } from 'devextreme-angular/ui/popup';
Move to root.

2024-01-30 19:53 UTC, mpreyskurantov commented on JSDemos/Demos/Charts/LoadDataOnDemand/Angular/app/app.component.ts
> +import { VisualRange } from 'devextreme-angular/common/charts';
Move before dextreme/data

2024-01-31 21:42 UTC, mpreyskurantov approved these changes

2024-02-01 10:28 UTC, dxvladislavvolkov approved these changes

2024-02-01 10:36 UTC, merged