Refactor types in Angular Demos p.4
DevExpress/devextreme-demos pull request #3077
Opened 2023-12-13 20:45 UTC by GoodDayForSurf

2024-02-05 06:21 UTC, mpreyskurantov requested changes

2024-02-05 06:21 UTC, mpreyskurantov commented on JSDemos/Demos/DataGrid/CascadingLookups/Angular/app/app.component.ts
>  import { DxDataGridModule } from 'devextreme-angular';
Group module and types to ui

2024-02-05 06:21 UTC, mpreyskurantov commented on JSDemos/Demos/DataGrid/CellEditingAndEditingAPI/Angular/app/app.component.ts
> +import { DxDataGridTypes } from 'devextreme-angular/ui/data-grid';
Group module, component and types to ui

2024-02-05 06:21 UTC, mpreyskurantov commented on JSDemos/Demos/DataGrid/CommandColumnCustomization/Angular/app/app.component.ts
>  import { DxDataGridModule } from 'devextreme-angular';
Group module and types to ui

2024-02-05 06:21 UTC, mpreyskurantov commented on JSDemos/Demos/DataGrid/CustomNewRecordPosition/Angular/app/app.component.ts
>  import { DxDataGridModule, DxSelectBoxModule } from 'devextreme-angular';
Group module and types to ui

2024-02-05 06:21 UTC, mpreyskurantov commented on JSDemos/Demos/DataGrid/CustomSummaries/Angular/app/app.component.ts
>  import { DxDataGridModule } from 'devextreme-angular';
Group module and types to ui

2024-02-05 06:21 UTC, mpreyskurantov commented on JSDemos/Demos/DataGrid/CustomizeKeyboardNavigation/Angular/app/app.component.ts
>    DxDataGridModule, DxButtonModule, DxCheckBoxModule, DxSelectBoxModule,
Group module and types to ui

2024-02-05 06:21 UTC, mpreyskurantov commented on JSDemos/Demos/DataGrid/DnDBetweenGrids/Angular/app/app.component.ts
>  import { DxDataGridModule } from 'devextreme-angular';
Group module and types to ui

2024-02-05 06:21 UTC, mpreyskurantov commented on JSDemos/Demos/DataGrid/EditStateManagement/Angular/app/app.component.ts
>  import { DxDataGridModule, DxLoadPanelModule } from 'devextreme-angular';
Group module and types to ui

2024-02-05 06:21 UTC, mpreyskurantov commented on JSDemos/Demos/DataGrid/FilterPanel/Angular/app/app.component.ts
>  import { DxDataGridModule } from 'devextreme-angular';
Group module and types to ui

2024-02-05 06:21 UTC, mpreyskurantov commented on JSDemos/Demos/DataGrid/Filtering/Angular/app/app.component.ts
> +  saleAmountHeaderFilter: DxoHeaderFilterComponent['dataSource'] = [{
@dxvladislavvolkov what do you think? may be not to use nested types?

2024-02-05 06:21 UTC, mpreyskurantov commented on JSDemos/Demos/DataGrid/FocusedRow/Angular/app/app.component.ts
> +import { DxDataGridTypes } from 'devextreme-angular/ui/data-grid';
Group module, component and types to ui

2024-02-05 06:21 UTC, mpreyskurantov commented on JSDemos/Demos/DataGrid/HorizontalVirtualScrolling/Angular/app/app.component.ts
> +import { DxDataGridTypes } from 'devextreme-angular/ui/data-grid';
Group module and types to ui

2024-02-05 06:21 UTC, mpreyskurantov commented on JSDemos/Demos/DataGrid/InfiniteScrolling/Angular/app/app.component.ts
> +import { DxDataGridComponent, DxDataGridModule } from 'devextreme-angular';
ui, module first

2024-02-05 06:21 UTC, mpreyskurantov commented on JSDemos/Demos/DataGrid/LocalReordering/Angular/app/app.component.ts
>  import { DxDataGridModule, DxCheckBoxModule } from 'devextreme-angular';
Group module and types to ui

2024-02-05 06:21 UTC, mpreyskurantov commented on JSDemos/Demos/DataGrid/MasterDetailAPI/Angular/app/app.component.ts
>  import { DxDataGridModule, DxTemplateModule } from 'devextreme-angular';
Group module and types to ui

2024-02-05 06:21 UTC, mpreyskurantov commented on JSDemos/Demos/DataGrid/MultipleSorting/Angular/app/app.component.ts
>  import { DxDataGridComponent, DxDataGridModule, DxCheckBoxModule } from 'devextreme-angular';
Group module and types to ui

2024-02-05 06:21 UTC, mpreyskurantov commented on JSDemos/Demos/DataGrid/Overview/Angular/app/app.component.ts
> +import { DxDataGridTypes } from 'devextreme-angular/ui/data-grid';
Group module and types to ui

2024-02-05 06:21 UTC, mpreyskurantov commented on JSDemos/Demos/DataGrid/PDFCellCustomization/Angular/app/app.component.ts
>  import { DxDataGridModule } from 'devextreme-angular';
Group module and types to ui

2024-02-05 06:21 UTC, mpreyskurantov commented on JSDemos/Demos/DataGrid/PDFExportImages/Angular/app/app.component.ts
>  import { DxDataGridModule } from 'devextreme-angular';
Group module and types to ui

2024-02-05 06:21 UTC, mpreyskurantov commented on JSDemos/Demos/DataGrid/PDFHeaderAndFooter/Angular/app/app.component.ts
>    DxDataGridModule, DxTemplateModule,
Group module and types to ui

2024-02-05 06:21 UTC, mpreyskurantov commented on JSDemos/Demos/DataGrid/PDFOverview/Angular/app/app.component.ts
>  import { DxDataGridModule } from 'devextreme-angular';
Group module and types to ui

2024-02-05 06:21 UTC, mpreyskurantov commented on JSDemos/Demos/DataGrid/RecalculateWhileEditing/Angular/app/app.component.ts
>  import { DxDataGridModule } from 'devextreme-angular';
Group module and types to ui

2024-02-05 06:21 UTC, mpreyskurantov commented on JSDemos/Demos/DataGrid/RemoteReordering/Angular/app/app.component.ts
>  import { DxDataGridModule } from 'devextreme-angular';
Group module and types to ui

2024-02-05 06:21 UTC, mpreyskurantov commented on JSDemos/Demos/DataGrid/ToolbarCustomization/Angular/app/app.component.ts
> +import { DxSelectBoxTypes } from 'devextreme-angular/ui/select-box';
Group module and types to ui

2024-02-05 06:21 UTC, mpreyskurantov commented on JSDemos/Demos/DataGrid/VirtualScrolling/Angular/app/app.component.ts
>  import { DxDataGridModule } from 'devextreme-angular';
Group module and types to ui

2024-02-07 07:02 UTC, dxvladislavvolkov approved these changes

2024-02-07 08:45 UTC, mpreyskurantov approved these changes

2024-02-07 08:46 UTC, merged