DataGrid: Remove Globalize from demos
DevExpress/devextreme-demos pull request #433
Opened 2020-12-02 12:47 UTC by jtoming830

2020-12-08 13:16 UTC, Alyar666 approved these changes, later dismissed

2020-12-08 15:10 UTC, vconst requested changes

2020-12-08 15:10 UTC, vconst commented on JSDemos/Demos/DataGrid/CellCustomization/AngularJS/index.js
> +                        `$${fieldData.value}` +
Use intl format
`DevExpress.localization.formatNumber(fieldData.value, {type: "currency", currency: "USD", precision: 2 })`
or ldml format
`DevExpress.localization.formatNumber(fieldData.value, "$#,##0.00")`
because group separators should be shown.

2020-12-10 13:26 UTC, vconst approved these changes

2020-12-11 09:08 UTC, Alyar666 approved these changes

2020-12-11 09:15 UTC, merged