treelist: add ctrl + l/r arrow, edit ctrl + u/d arrow; datagrid: edit ctrl + u/d arrow
DevExpress/devextreme-demos pull request #535
Opened 2021-01-19 11:19 UTC by pavel-2020

[Trello card](https://trello.com/c/Q7w6dWMq/1487-add-description-for-keys-to-treelist-keyboard-navigation)

2021-01-19 16:08 UTC, RomanTsukanov requested changes
In both lists, item headers and item descriptions are displayed in one line. Don't forget about 4 or more space characters after the item header.

2021-01-19 16:08 UTC, RomanTsukanov commented on JSDemos/Demos/DataGrid/KeyboardNavigation/description.md
> +Navigate between TreeList elements.
```suggestion
Navigate within DataGrid elements.
```

2021-01-19 16:08 UTC, RomanTsukanov commented on JSDemos/Demos/TreeList/KeyboardNavigation/description.md
>  Navigate between TreeList elements.
```suggestion
Navigate within TreeList elements.
```

2021-01-20 09:56 UTC, RomanTsukanov approved these changes, later dismissed

2021-01-21 08:27 UTC, dirk-pieterse approved these changes, later dismissed

2021-01-21 08:27 UTC, dirk-pieterse commented on JSDemos/Demos/DataGrid/KeyboardNavigation/description.md
> +Navigate between column header, filter row, data area, filter panel, and pager.
```suggestion
Navigate between a column header, filter row, data area, filter panel, and pager.
```

2021-01-21 08:27 UTC, dirk-pieterse commented on JSDemos/Demos/TreeList/KeyboardNavigation/description.md
> +Navigate between column header, filter row, data area, filter panel, and pager.
```suggestion
Navigate between a column header, filter row, data area, filter panel, and pager.
```

2021-01-21 13:45 UTC, RomanTsukanov approved these changes

2021-01-22 13:52 UTC, merged