20_2 TreeList Cell Editing: rewrite
DevExpress/devextreme-demos pull request #739
Opened 2021-04-09 14:37 UTC by pavel-2020

The text is based on https://github.com/DevExpress/devextreme-demos/blob/20842f6a158b112ac83d9df67cdf0b542d6a781f/JSDemos/Demos/DataGrid/CellEditingAndEditingAPI/description.md

2021-04-12 12:51 UTC, AlexJameson commented on JSDemos/Demos/TreeList/CellEditing/description.md
> +When a user presses the button to add a new row, the [onInitNewRow](/Documentation/ApiReference/UI_Components/dxTreeList/Configuration/#onInitNewRow) handler populates the new row editor with data. I
> this function preselects *Not Started* in the `Status` drop-down field

This is not a drop-down field. The drop-down field is on the screenshot: 
![image](https://user-images.githubusercontent.com/33040934/114396701-826d2700-9ba6-11eb-9263-5fb44f0789e2.png)

Also I still don't get what is a 'row editor'

2021-04-14 06:30 UTC, AlexJameson commented on JSDemos/Demos/TreeList/CellEditing/description.md
> +When a user presses the button to add a new row, the [onInitNewRow](/Documentation/ApiReference/UI_Components/dxTreeList/Configuration/#onInitNewRow) handler populates cells of a new row with default
I feel like some formatting is required for the mentioned fields:

```suggestion
When a user presses the button to add a new row, the [onInitNewRow](/Documentation/ApiReference/UI_Components/dxTreeList/Configuration/#onInitNewRow) handler populates cells of a new row with default values. In this demo, this function sets *Not Started* as `Status` and current date as `Start Date` and `Due Date`.
```

2021-04-14 14:58 UTC, AlexJameson approved these changes, later dismissed

2021-04-15 12:16 UTC, RomanTsukanov requested changes

2021-04-15 12:16 UTC, RomanTsukanov commented on JSDemos/Demos/TreeList/CellEditing/description.md
> +When a user presses the button to add a new row, the [onInitNewRow](/Documentation/ApiReference/UI_Components/dxTreeList/Configuration/#onInitNewRow) handler populates cells of a new row with default
```suggestion
This demo also shows how to populate cells of a new row with default values. The values are assigned within the [onInitNewRow](/Documentation/ApiReference/UI_Components/dxTreeList/Configuration/#onInitNewRow) event handler.
```

2021-04-16 08:14 UTC, RomanTsukanov approved these changes, later dismissed

2021-04-16 09:11 UTC, AlexJameson approved these changes, later dismissed

2021-04-16 15:48 UTC, arminal commented on JSDemos/Demos/TreeList/CellEditing/description.md
> +Users can modify TreeList data cell by cell. In this mode, only one cell can be in the edit state at a time. TreeList saves changes immediately after the focus leaves cell.
```suggestion
Users can modify TreeList data cell by cell. In this mode, only one cell can be in the edit state at a time. The TreeList saves changes immediately after the focus leaves cell.
```
the focus leaves cell? rephrase

2021-04-16 15:48 UTC, arminal commented on JSDemos/Demos/TreeList/CellEditing/description.md
> +To enable the cell mode, do the following:
```suggestion
To enable cell mode, do the following:
```

2021-04-16 15:48 UTC, arminal commented on JSDemos/Demos/TreeList/CellEditing/description.md
> +- Set the **editing**.[mode](/Documentation/ApiReference/UI_Components/dxTreeList/Configuration/editing/#mode) to *"cell*".
```suggestion
- Set  **editing** [mode](/Documentation/ApiReference/UI_Components/dxTreeList/Configuration/editing/#mode) to *"cell*".
```

2021-04-19 08:14 UTC, RomanTsukanov requested changes

2021-04-19 08:14 UTC, RomanTsukanov commented on JSDemos/Demos/TreeList/CellEditing/description.md
> +- Set  **editing** [mode](/Documentation/ApiReference/UI_Components/dxTreeList/Configuration/editing/#mode) to *"cell*".
```suggestion
- Set the **editing**.[mode](/Documentation/ApiReference/UI_Components/dxTreeList/Configuration/editing/#mode) property to *"cell*".
```

2021-04-19 14:21 UTC, RomanTsukanov approved these changes

2021-04-19 15:47 UTC, merged