20_2 TreeList Form Editing: rewrite
DevExpress/devextreme-demos pull request #758
Opened 2021-04-14 13:19 UTC by pavel-2020

[Trello](https://trello.com/c/gGAbEsoc/1650-treelist-demos-editing-5-demos)

2021-04-20 06:34 UTC, AlexJameson commented on JSDemos/Demos/TreeList/FormEditing/description.md
> +This demo uses form editing mode and illustrates the following event handlers:
I think its is quite obvious:

```suggestion
This demo also illustrates the following event handlers:
```

2021-04-20 06:34 UTC, AlexJameson commented on JSDemos/Demos/TreeList/FormEditing/description.md
> +Populates form editors of a new row with default values. In this demo, **onInitNewRow** sets John Heart as the initial Head for new rows.
```suggestion
Populates form editors of a new row with default values. In this demo, **onInitNewRow** sets *"John Heart"* as the initial `Head` for new rows.
```

2021-04-20 06:34 UTC, AlexJameson commented on JSDemos/Demos/TreeList/FormEditing/description.md
> +Customizes form editors. In this demo, this handler disallows users to edit the Head value of John Heart.
```suggestion
Customizes form editors. In this demo, this handler disallows users to edit the `Head` value of John Heart.
```

2021-04-21 16:33 UTC, RomanTsukanov requested changes

2021-04-21 16:33 UTC, RomanTsukanov commented on JSDemos/Demos/TreeList/FormEditing/description.md
> +A column's default editor is defined automatically based on this column's [dataType](/Documentation/ApiReference/UI_Components/dxTreeList/Configuration/columns/#dataType). To customize this editor or
Two sentences in a row end with the same phrase.

```suggestion
A column's default editor is defined automatically based on this column's [dataType](/Documentation/ApiReference/UI_Components/dxTreeList/Configuration/columns/#dataType). To customize this editor or replace it with another editor, use the column's [formItem](/Documentation/ApiReference/UI_Components/dxTreeList/Configuration/columns/#formItem) object. For information on settings that you can define in the **formItem** object, refer to the [SimpleItem](/Documentation/ApiReference/UI_Components/dxForm/Item_Types/SimpleItem/) help topic.
```

2021-04-21 16:33 UTC, RomanTsukanov commented on JSDemos/Demos/TreeList/FormEditing/description.md
> +You can also set up the edit Form from scratch. The component's [configuration section](/Documentation/ApiReference/UI_Components/dxForm/) lists available settings. Specify these settings in the **ed
No information about the limitations has been given yet.

```suggestion
You can also set up the edit Form from scratch. The component's [configuration section](/Documentation/ApiReference/UI_Components/dxForm/) lists available settings. Specify these settings in the **editing**.[form](/Documentation/ApiReference/UI_Components/dxTreeList/Configuration/editing/#form) object. Refer to this object's description for information about form edit mode's limitations.
```

2021-04-27 08:30 UTC, RomanTsukanov approved these changes, later dismissed

2021-04-27 14:17 UTC, AlexJameson submitted a review, later dismissed

2021-04-27 19:01 UTC, dmitry-eliseev-devexpress commented on JSDemos/Demos/TreeList/FormEditing/description.md
> +You can also set up the edit Form from scratch. The component's [configuration section](/Documentation/ApiReference/UI_Components/dxForm/) lists available settings. Specify these settings in the **ed
```suggestion
You can also set up the edit Form from scratch. The component's [configuration section](/Documentation/ApiReference/UI_Components/dxForm/) lists available settings. Specify these settings in the **editing**.[form](/Documentation/ApiReference/UI_Components/dxTreeList/Configuration/editing/#form) object. Refer to this object's description for information about form edit mode limitations.
```

2021-04-27 19:01 UTC, dmitry-eliseev-devexpress commented on JSDemos/Demos/TreeList/FormEditing/description.md
> +Customizes form editors. In this demo, this handler disallows users to edit the `Head` value of John Heart.
**dis**allows is a negative statement. It's better to choose a word that does not require negation to convey the same idea.

```suggestion
Customizes form editors. In this demo, this handler forbids users to edit the `Head` value of John Heart.
```

2021-04-27 19:01 UTC, dmitry-eliseev-devexpress commented on JSDemos/Demos/TreeList/FormEditing/description.md
> +TreeList can use the [Form](/Documentation/ApiReference/UI_Components/dxForm/) component to arrange cell editors when users modify a row. Users can edit values in [visible](/Documentation/ApiReferenc
From what I understand, the editors on the Form allow users to modify values both in visible and hidden columns. However, the second sentence here does not convey this idea clearly enough. Right now to me it sounds like users always can edit all kinds of columns. Please take another look at this paragraph. You most likely can come up with something better.

2021-04-30 12:13 UTC, dirk-pieterse approved these changes, later dismissed

2021-04-30 12:13 UTC, dirk-pieterse commented on JSDemos/Demos/TreeList/FormEditing/description.md
> +The TreeList can use the [Form](/Documentation/ApiReference/UI_Components/dxForm/) component to arrange cell editors when users modify a row. The Form allows users to edit values from both [visible a
```suggestion
The TreeList can use the [Form](/Documentation/ApiReference/UI_Components/dxForm/) component to arrange cell editors when users modify a row. The Form allows users to edit values from [visible and hidden](/Documentation/ApiReference/UI_Components/dxTreeList/Configuration/columns/#visible) columns.
```

2021-04-30 12:13 UTC, dirk-pieterse commented on JSDemos/Demos/DataGrid/FormEditing/description.md
> +The DataGrid can use the [Form](/Documentation/ApiReference/UI_Components/dxForm/) component to arrange cell editors when users modify a row. The Form allows users to edit values from both [visible a
```suggestion
The DataGrid can use the [Form](/Documentation/ApiReference/UI_Components/dxForm/) component to arrange cell editors when users modify a row. The Form allows users to edit values from [visible and hidden](/Documentation/ApiReference/UI_Components/dxDataGrid/Configuration/columns/#visible) columns (see the `Notes` column).
```

2021-04-30 13:46 UTC, RomanTsukanov approved these changes

2021-04-30 13:50 UTC, merged