20_2 TreeList Column Reordering: rewrite
DevExpress/devextreme-demos pull request #795
Opened 2021-04-21 14:47 UTC by pavel-2020

[Trello](https://trello.com/c/Bi9lS4Ee/1654-treelist-demos-column-customization-4-demos)

2021-04-28 09:35 UTC, AlexJameson commented on JSDemos/Demos/TreeList/Reordering/description.md
> +The initial order of columns mirrors the order of fields in the first object from the [dataSource](/Documentation/ApiReference/UI_Components/dxTreeList/Configuration/#dataSource). You can change that
The first sentence is not true, see the screenshot. In my opinion, the whole concept is misleading. Are there many cases when users create a TreeList without the **columns** property?

![image](https://user-images.githubusercontent.com/33040934/116368813-63f76480-a811-11eb-8dc3-735bc467d23c.png)

2021-04-28 09:35 UTC, AlexJameson commented on JSDemos/Demos/TreeList/Reordering/description.md
> +* [columns[]](/Documentation/ApiReference/UI_Components/dxTreeList/Configuration/columns/)
```suggestion
* **[columns[]](/Documentation/ApiReference/UI_Components/dxTreeList/Configuration/columns/)**           
```

2021-04-28 09:35 UTC, AlexJameson commented on JSDemos/Demos/TreeList/Reordering/description.md
> +Configures columns. Arrange column names and objects in the desired order.
```suggestion
Configures columns. Arrange column names or data objects in the desired order.
```

2021-04-28 09:35 UTC, AlexJameson commented on JSDemos/Demos/TreeList/Reordering/description.md
> +**Property that enables users to reorder columns:**
I'm not sure that a list with only one item is a good idea. I think that it's better to transform the list to a regular paragraph or move the **allowReordering** description to a separate list item.

2021-04-28 09:40 UTC, AlexJameson commented on JSDemos/Demos/TreeList/Reordering/description.md
> +Specifies the position of the column regarding other columns. For details, see the [Column Reordering](https://js.devexpress.com/Documentation/Guide/UI_Components/TreeList/Columns/Column_Reordering/)
```suggestion
Specifies the position of the column regarding other columns. For details, see the [Column Reordering](/Documentation/Guide/UI_Components/TreeList/Columns/Column_Reordering/) article.
```

2021-05-13 10:46 UTC, AlexJameson approved these changes, later dismissed

2021-05-13 10:46 UTC, AlexJameson commented on JSDemos/Demos/TreeList/Reordering/description.md
> +To reorder columns in code, arrange objects and column names as strings in the desired order inside the [columns[]](/Documentation/ApiReference/UI_Components/dxTreeList/Configuration/columns/) array.
```suggestion
To reorder columns in code, arrange objects and column names as strings in the desired order inside the [columns[]](/Documentation/ApiReference/UI_Components/dxTreeList/Configuration/columns/) array. Additionally, you can use the **columns[]**.[visibleIndex](/Documentation/ApiReference/UI_Components/dxTreeList/Configuration/columns/#visibleIndex) property to specify the position of the column regarding other columns. For details, see the [Column Reordering](/Documentation/Guide/UI_Components/TreeList/Columns/Column_Reordering/) article.
```

2021-05-14 11:28 UTC, RomanTsukanov requested changes

2021-05-14 11:28 UTC, RomanTsukanov commented on JSDemos/Demos/TreeList/Reordering/description.md
> +The structure of [dataSource](/Documentation/ApiReference/UI_Components/dxTreeList/Configuration/#dataSource) objects defines the order of TreeList columns. You can change the order programmatically
> The structure of [dataSource](/Documentation/ApiReference/UI_Components/dxTreeList/Configuration/#dataSource) objects defines the order of TreeList columns.

First the old ("the order of columns"), then the new ("is defined by the structure of data objects").

Also, there's little information to divide the description into subheadings, so I moved information from the following paragraph here.

```suggestion
The order of TreeList columns is the same as the order of fields in data objects. You can use the [columns](/Documentation/ApiReference/UI_Components/dxTreeList/Configuration/columns/) array to specify a different order. To reorder a column at runtime, change its [visibleIndex](/Documentation/ApiReference/UI_Components/dxTreeList/Configuration/columns/#visibleIndex) property.
```

2021-05-14 11:28 UTC, RomanTsukanov commented on JSDemos/Demos/TreeList/Reordering/description.md
> +To reorder columns in code, arrange objects and column names as strings in the desired order inside the [columns[]](/Documentation/ApiReference/UI_Components/dxTreeList/Configuration/columns/) array.
```suggestion
```

2021-05-14 11:28 UTC, RomanTsukanov commented on JSDemos/Demos/TreeList/Reordering/description.md
> +To enable column reorder in the UI, set [allowColumnReordering](/Documentation/ApiReference/UI_Components/dxTreeList/Configuration/#allowColumnReordering) to **true**. If some column should never be
I added how users reorder columns and change this bit:

> If some column should never be reordered

to make clear what exactly happens when you disable a column's `allowReordering`.

```suggestion
Users can drag and drop column headers to reorder columns. To enable this feature, set the [allowColumnReordering](/Documentation/ApiReference/UI_Components/dxTreeList/Configuration/#allowColumnReordering) property to **true**. If you do not want users to drag a specific column, disable its [allowReordering](/Documentation/ApiReference/UI_Components/dxTreeList/Configuration/columns/#allowReordering) property.
```

2021-05-17 08:31 UTC, RomanTsukanov submitted a review, later dismissed

2021-05-25 17:42 UTC, dmitry-eliseev-devexpress submitted a review, later dismissed

2021-05-25 17:42 UTC, dmitry-eliseev-devexpress commented on JSDemos/Demos/TreeList/Reordering/description.md
> +The order of TreeList columns is the same as the order of fields in data objects. You can use the [columns](/Documentation/ApiReference/UI_Components/dxTreeList/Configuration/columns/) array to speci
```suggestion
The order of TreeList columns follows the order of fields in data objects. You can use the [columns](/Documentation/ApiReference/UI_Components/dxTreeList/Configuration/columns/) array to specify a different order. To reorder a column at runtime, change its [visibleIndex](/Documentation/ApiReference/UI_Components/dxTreeList/Configuration/columns/#visibleIndex) property.
```

2021-05-26 11:39 UTC, dirk-pieterse submitted a review, later dismissed

2021-05-26 11:39 UTC, dirk-pieterse commented on JSDemos/Demos/TreeList/Reordering/description.md
> +The order of TreeList columns follows the order of fields in data objects. You can use the [columns](/Documentation/ApiReference/UI_Components/dxTreeList/Configuration/columns/) array to specify a di
```suggestion
TreeList columns have the same order as fields in data objects. You can use the [columns](/Documentation/ApiReference/UI_Components/dxTreeList/Configuration/columns/) array to specify a different order. To reorder a column at runtime, change its [visibleIndex](/Documentation/ApiReference/UI_Components/dxTreeList/Configuration/columns/#visibleIndex) property.
```

2021-05-26 14:53 UTC, RomanTsukanov approved these changes

2021-05-26 15:01 UTC, merged