Update the description for DataGrid - Adaptability Overview
DevExpress/devextreme-demos pull request #82
Opened 2020-08-26 14:19 UTC by AlexJameson

https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/GridAdaptabilityOverview/jQuery/Light/

2020-08-26 14:52 UTC, RomanTsukanov requested changes

2020-08-26 14:52 UTC, RomanTsukanov commented on JSDemos/Demos/DataGrid/GridAdaptabilityOverview/description.md
> +**DataGrid** automatically adapts its layout to screens of different widths. Use buttons in the top right corner to switch between the mobile and tablet screens. If columns do not fit the chosen scre
```suggestion
**DataGrid** automatically adapts its layout to screens of different widths. In this demo, you can switch between horizontal and vertical screen orientations. If columns do not fit the chosen orientation, the widget hides them one by one, starting with the rightmost column. Information from the hidden columns is still available in adaptive detail rows.
```

2020-08-26 14:52 UTC, RomanTsukanov commented on JSDemos/Demos/DataGrid/GridAdaptabilityOverview/description.md
> +**DataGrid** displays hidden columns' data in the adaptive row as [Form](/Documentation/Guide/Widgets/Form/Overview/) items. You can use the [onAdaptiveDetailRowPreparing](/Documentation/ApiReference
The paragraph looks unnecessary. This handler does allow you to customize the adaptive detail row, but it seems that only few customers really need that. And the demo doesn't show this handler.

> Refer to the handler's description to see the limitations.

I think we mention limitations too often, it makes us look bad. We shouldn't do that unless the limitations are serious and easy to encounter.

2020-08-27 07:37 UTC, RomanTsukanov approved these changes, later dismissed

2020-09-02 21:32 UTC, Abadzhev reviewed
Looks good to me. Thanks.

2020-09-08 05:54 UTC, dirk-pieterse submitted a review, later dismissed

2020-09-08 05:54 UTC, dirk-pieterse commented on JSDemos/Demos/DataGrid/GridAdaptabilityOverview/description.md
> +**DataGrid** automatically adapts its layout to screens of different widths. In this demo, you can switch between horizontal and vertical screen orientations. If columns do not fit the chosen orienta
```suggestion
**DataGrid** automatically adapts its layout to screens with different sizes. In this demo, you can switch between horizontal and vertical screen orientations. If columns do not fit the selected orientation, the widget hides them one by one, starting with the rightmost column. Information from the hidden columns is still available in adaptive detail rows.
```

2020-09-08 05:54 UTC, dirk-pieterse commented on JSDemos/Demos/DataGrid/GridAdaptabilityOverview/description.md
> +To enable this behavior in your application, set the [columnHidingEnabled](/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/#columnHidingEnabled) option to **true**.
```suggestion
To enable this feature, set the [columnHidingEnabled](/Documentation/ApiReference/UI_Widgets/dxDataGrid/Configuration/#columnHidingEnabled) option to **true**.
```

2020-09-08 11:31 UTC, pavel-2020 commented on JSDemos/Demos/DataGrid/GridAdaptabilityOverview/description.md
> +**DataGrid** automatically adapts its layout to screens with different sizes. In this demo, you can switch between horizontal and vertical screen orientations. If columns do not fit the selected orie
"Information from the hidden columns is still available in **adaptive detail rows**."
This sentence left me wondering what these 'adaptive detail rows' are.  The sentence from the previous version of  the demo description explains this concept better: "To view values of hidden columns, click the ellipsis button in the last column of the required row.", doesn't it?

2020-09-08 12:16 UTC, pavel-2020 approved these changes

2020-09-08 14:13 UTC, merged