Scheduler Resources demo: rewrite
DevExpress/devextreme-demos pull request #872
Opened 2021-05-17 16:03 UTC by pavel-2020

[Trello](https://trello.com/c/zVjxbHQf/1667-scheduler-demos-resources-1-demo)
[Demo](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Scheduler/Resources/jQuery/Light/)

2021-05-19 11:42 UTC, AlexJameson commented on JSDemos/Demos/Scheduler/Resources/description.md
> +A resource (resource kind) adds an appointment field that allows users to assign the appointment to a single or multiple categories. The appointment rectangle will have the color based on the selecte
1. Why add 'resource kind' in this sentence? 

2. >it derives the color scheme from the last resource kind object

Last object in the `resources[]` array?

2021-05-19 11:42 UTC, AlexJameson commented on JSDemos/Demos/Scheduler/Resources/description.md
> +Resource instances are objects that define the available categories. Each resource instance object must contain the id, text, and color fields. Create an array of such objects. If your field names di
It is not completely clear where users should specify these properties. Also please add the Oxford comma.

2021-05-19 11:42 UTC, AlexJameson commented on JSDemos/Demos/Scheduler/Resources/description.md
> +Create one resource kind object. To enable multiple category selection, set the object's [allowMultiple](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/resources/#allowMultiple)
You've already described how to create such object. This sentence would be more appropriate in a tutorial, IMHO.

```suggestion
To enable multiple category selection, set the object's [allowMultiple](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/resources/#allowMultiple) property to **true**. 
```

2021-05-19 11:42 UTC, AlexJameson commented on JSDemos/Demos/Scheduler/Resources/description.md
> +By now, users should be able to select categories in the newly created appointment form field.
The same note about tutorial as above.

2021-05-19 11:42 UTC, AlexJameson commented on JSDemos/Demos/Scheduler/Resources/description.md
> +To associate a specific appointment with the resource, include a field specified in the **fieldExpr** property into the appointment's data object. This field should be equal to one of the appointment
We can preset something only in code, right? I also don't think that the word optionally is a good choice for a heading. The last point - Ray doesn't like apostrophes after plurals.

```suggestion
### Preset appointments to specific categories
To associate a specific appointment with the resource, include a field specified in the **fieldExpr** property into the appointment's data object. This field's should be equal to id of one of the appointment instances.
```

2021-05-19 15:39 UTC, AlexJameson commented on JSDemos/Demos/Scheduler/Resources/description.md
> +### Add resource instances
Let's use the title case here and below

2021-05-21 11:47 UTC, AlexJameson commented on JSDemos/Demos/Scheduler/Resources/description.md
> +    Maps a resource kind to resource instances. For details on how to provide data, see the [Data Binding](/Documentation/Guide/Data_Binding/Specify_a_Data_Source/Local_Array/) help topics.
To be honest, I don't get what the first sentence means. Doesn't the dataSource bind a resource to data?

2021-05-21 11:47 UTC, AlexJameson commented on JSDemos/Demos/Scheduler/Resources/description.md
> +    Specifies the name of an appointment data field that assigns the appointment to a specific category id.
The word category seems a bit confusing here. Maybe rephrase this sentence a bit to use the word 'resource' instead?

2021-05-21 11:47 UTC, AlexJameson commented on JSDemos/Demos/Scheduler/Resources/description.md
> +To enable multiple category selection, set the object's [allowMultiple](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/resources/#allowMultiple) property to **true**.
The same question about category

2021-05-24 10:39 UTC, RomanTsukanov requested changes

2021-05-24 10:39 UTC, RomanTsukanov commented on JSDemos/Demos/Scheduler/Resources/description.md
> +The Scheduler can have multiple resources. To add a resource, do the following:
The subheadings are self-explanatory.

```suggestion
```

2021-05-24 10:39 UTC, RomanTsukanov commented on JSDemos/Demos/Scheduler/Resources/description.md
> +Each object should have at least the following fields:
> array property

So is this an array or property?

It's not a good idea to create a two-item list where the first item contains a nested list and the second item is optional.

```suggestion
Use the [resources](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/resources/) array to define resource kinds. Each object in this array should contain at least the following fields:
```

2021-05-24 10:39 UTC, RomanTsukanov commented on JSDemos/Demos/Scheduler/Resources/description.md
> +### Define Resources
We agreed upon the terms we're going to use, now let's use them.

```suggestion
### Define Resource Kinds
```

2021-05-24 10:39 UTC, RomanTsukanov commented on JSDemos/Demos/Scheduler/Resources/description.md
> +    Each resource instance object should contain the id, text, and color fields. If your field names differ, specify them in the global [valueExpr](/Documentation/ApiReference/UI_Components/dxSchedul
Crossed out unnecessary words. We need to be succinct, especially when giving explanations in lists.

```suggestion
- [dataSource](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/resources/#dataSource)         
    Resource instances of this resource kind. Each instance should contain the `id`, `text`, and `color` fields. If your field names differ, specify them in the [valueExpr](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/resources/#valueExpr), [displayExpr](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/resources/#displayExpr), and [colorExpr](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/resources/#colorExpr) properties, respectively.

```

2021-05-24 10:39 UTC, RomanTsukanov commented on JSDemos/Demos/Scheduler/Resources/description.md
> +Include a field specified in the **fieldExpr** property into appointment data objects. The field should be equal to a resource instance id. If you skip this step, users should specify resource instan
"Preset appointments to specific resource instances" is the main use case for fieldExpr. It should be described in the fieldExpr description.

This is also a good place to refer to the demo code.

```suggestion
- [fieldExpr](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/resources/#fieldExpr)             
    A data field used to assign instances of this resource kind to appointments. Add this field to appointment objects and set its value to resource instance `id`s.

In this demo, the **resources** array contains three resource kinds: rooms, priorities, and owners. Their **fieldExpr** values are `roomId`, `priorityId`, and `ownerId`. Each appointment contains the same fields. Field values assign the appointments to different instances of these resource kinds.
```

2021-05-24 10:39 UTC, RomanTsukanov commented on JSDemos/Demos/Scheduler/Resources/description.md
> +The Scheduler uses the color scheme of the last resource kind object in the **resources** array. If you need colors of another object, set its [useColorAsDefault](/Documentation/ApiReference/UI_Compo
If you need to describe the default state of things, see if you can start with describing how to change it and mention the default values in the end. Note how I did this below.

Also, don't forget to demo.

```suggestion
### Color Appointments Based on Resource Kind

To use the color scheme of a specific resource kind, enable the kind's [useColorAsDefault](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/resources/#useColorAsDefault) property. Otherwise, appointments use the color scheme of the last resource kind declared in the **resources** array.

This demo enables you to change the **useColorAsDefault** property at runtime. Click the radio buttons under the Scheduler to switch between different color schemes.
```

2021-05-24 10:39 UTC, RomanTsukanov commented on JSDemos/Demos/Scheduler/Resources/description.md
> +Users can categorize appointments by resources. To understand what resources are, consider the following example: in an educational center lectures are held in several rooms. In Scheduler terms, room
```suggestion
Users can categorize appointments by resources. To understand what resources are, consider the following example: in an educational center lectures are held in several rooms. In Scheduler terms, room is a resource kind, individual rooms are resource instances, and lectures are appointments that use these resource instances.
```

2021-05-24 10:39 UTC, RomanTsukanov commented on JSDemos/Demos/Scheduler/Resources/description.md
> +To enable assignment of multiple resource instances, set the resource object's [allowMultiple](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/resources/#allowMultiple) property t
Multiple instances of a **single resource kind** - this is important.
We need to do a better job explaining what is what, not just "to enable this, do that".

```suggestion
### Assign Multiple Instances of a Resource Kind

Each resource kind object can contain the [allowMultiple](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/resources/#allowMultiple) property. When it is **true**, users can assign multiple instances of this kind to a single appointment. In this demo, the Owner resource kind allows multiple instances.
```

2021-05-24 10:39 UTC, RomanTsukanov commented on JSDemos/Demos/Scheduler/Resources/description.md
> +You can also group appointments by resources as specified in the following article: [Group Appointments by Resources](/Documentation/Guide/UI_Components/Scheduler/Resources/Group_Appointments_by_Reso
We have a demo that's gonna be the main source of information on this scenario:

```suggestion
You can also group appointments by resources as shown in the following demo: [Group Orientation](/Demos/WidgetsGallery/Demo/Scheduler/GroupOrientation/). 
```

2021-05-26 11:05 UTC, RomanTsukanov submitted a review, later dismissed

2021-06-03 08:05 UTC, NikolaevaIrina commented on JSDemos/Demos/Scheduler/Resources/description.md
> +### Define Resource Kinds
Привет :) Я нигде не нашла такого термина Resource Kinds, везде они называются Resource Types (я просто гуглить пробовала). Может быть переименовать? Если же это термин, то я не возражаю)

2021-06-03 08:05 UTC, NikolaevaIrina commented on JSDemos/Demos/Scheduler/Resources/description.md
> +Use the [resources](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/resources/) array to define resource kinds. Each object in this array should contain at least the following fie
Как именно можно использовать этот массив? В него нужно добавлять объекты с указанными полями? Если так, то может быть так и сказать "Добавьте все необходимые типы ресурсов в такой-то массив?" Или как-то подобный образом.

Плюс, мне кажется, из второго предложения можно убрать at least (should вроде бы и так сожержит нужный смысл):
Each object in this array should contain the following fields:

2021-06-03 08:05 UTC, NikolaevaIrina commented on JSDemos/Demos/Scheduler/Resources/description.md
> +    A data field used to assign instances of this resource kind to appointments. Add this field to appointment objects and set its value to resource instance `id`s.
```suggestion
    A data field used to assign instances of this resource kind to appointments. Add this field to appointment objects and set the field value to a resource instance's `id` values.
```

2021-06-03 08:05 UTC, NikolaevaIrina commented on JSDemos/Demos/Scheduler/Resources/description.md
> +In this demo, the **resources** array contains three resource kinds: rooms, priorities, and owners. Their **fieldExpr** values are `roomId`, `priorityId`, and `ownerId`. Each appointment contains the
```suggestion
In this demo, the **resources** array contains three resource kinds: rooms, priorities, and owners. Their **fieldExpr** values are `roomId`, `priorityId`, and `ownerId`, respectively. Each appointment contains the same fields. Field values assign the appointments to different instances of these resource kinds.
```

2021-06-03 08:05 UTC, NikolaevaIrina commented on JSDemos/Demos/Scheduler/Resources/description.md
> +### Color Appointments Based on Resource Kind
```suggestion
### Color Appointments Based on a Resource Kind
```

2021-06-03 08:05 UTC, NikolaevaIrina commented on JSDemos/Demos/Scheduler/Resources/description.md
> +Each resource kind object can contain the [allowMultiple](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/resources/#allowMultiple) property. When it is **true**, users can assign
```suggestion
Each resource kind object can contain the [allowMultiple](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/resources/#allowMultiple) property. When this property is set to **true**, users can assign multiple instances of this kind to a single appointment. In this demo, the Owner resource kind allows multiple instances.
```

2021-06-04 08:28 UTC, dirk-pieterse approved these changes, later dismissed

2021-06-04 08:28 UTC, dirk-pieterse commented on JSDemos/Demos/Scheduler/Resources/description.md
> +Users can categorize appointments by resources. To understand what resources are, consider the following example: in an educational center lectures are held in several rooms. In Scheduler terms, room
```suggestion
Users can categorize appointments by resources. The following example illustrates what resources are: in an educational center lectures are held in several rooms. In Scheduler terms, room is a resource kind, individual rooms are resource instances, and lectures are appointments that use these resource instances.
```

2021-06-04 08:28 UTC, dirk-pieterse commented on JSDemos/Demos/Scheduler/Resources/description.md
> +Use the [resources](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/resources/) array to define resource kinds. Each object in this array should contain at least the following fie
Why `kinds` and not **types**?

2021-06-04 08:34 UTC, pavel-2020 commented on JSDemos/Demos/Scheduler/Resources/description.md
> +Use the [resources](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/resources/) array to define resource kinds. Each object in this array should contain at least the following fie
"Resource kind" is a term. It is introduced in the first paragraph of this text.

2021-06-04 08:41 UTC, dirk-pieterse commented on JSDemos/Demos/Scheduler/Resources/description.md
> +Use the [resources](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/resources/) array to define resource kinds. Each object in this array should contain at least the following fie
Ok

2021-06-04 12:41 UTC, RomanTsukanov approved these changes

2021-06-04 12:47 UTC, merged