Scheduler Grouping: rewrite
DevExpress/devextreme-demos pull request #877
Opened 2021-05-19 11:41 UTC by pavel-2020

[Trello](https://trello.com/c/lTA2NdUk/1668-scheduler-demos-grouping-2-demos)
[Demo](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Scheduler/GroupOrientation)

2021-05-24 09:11 UTC, AlexJameson commented on JSDemos/Demos/Scheduler/GroupOrientation/description.md
> +If resources are assigned to appointments, you can group them by these resources. To do so, use the [groups](/api-reference/10%20UI%20Components/dxScheduler/1%20Configuration/groups.md '/Documentatio
>If resources are assigned to appointments, you can group them by these resources. 

Please add links to appointments and resources.

>To do so, use the [groups](/api-reference/10%20UI%20Components/dxScheduler/1%20Configuration/groups.md '/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/#groups') property to specify an array. 

This sentence breaks suddenly. How about changing it a bit as follows: To do this, specify the [groups[]]() array. 

>Each element of this array is **fieldExpr** of a resource kind. 

Let's add a link.
 
>Note that the resource headers' order depends on the resources' order in the [resources]() array.

Once again, I suggest you not to use apostrophes with plurals. How about this: Note that the order of resource headers depends on the order of elements in the **resources[]** array.

2021-05-24 09:11 UTC, AlexJameson commented on JSDemos/Demos/Scheduler/GroupOrientation/description.md
> +The Scheduler arranges group headers vertically (in a column) or horizontally (in a row). This depends on the view type. You can use the **views**.[groupOrientation](/api-reference/10%20UI%20Componen
```suggestion
The Scheduler arranges group headers vertically (in a column) or horizontally (in a row). This depends on the view [type](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/views/#type). You can use the **views**.[groupOrientation](/api-reference/10%20UI%20Components/dxScheduler/1%20Configuration/views/groupOrientation.md '/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/views/#groupOrientation') property to set custom orientation for specific views.
```

2021-05-25 14:11 UTC, AlexJameson submitted a review, later dismissed

2021-05-27 10:00 UTC, RomanTsukanov requested changes

2021-05-27 10:00 UTC, RomanTsukanov commented on JSDemos/menuMeta.json
> +        "Name": "Group Appointments",
We aggreed to keep the old names.

2021-05-27 10:00 UTC, RomanTsukanov commented on JSDemos/Demos/Scheduler/GroupOrientation/description.md
> +If [resources](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/resources/) are assigned to appointments, you can group them by these resources. To do this, specify the [groups](/a
Let's look at the description from the standpoint of a reader who doesn't know about resource. We should first introduce him to the concept, give a link to the Resources demo, and only then go on about grouping.

2021-05-27 10:00 UTC, RomanTsukanov commented on JSDemos/Demos/Scheduler/GroupOrientation/description.md
> +The Scheduler arranges group headers vertically (in a column) or horizontally (in a row). This depends on the view [type](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/views/#ty
Use only URLs in links within demo descriptions.

2021-05-31 07:56 UTC, RomanTsukanov requested changes

2021-05-31 07:56 UTC, RomanTsukanov commented on JSDemos/Demos/Scheduler/GroupOrientation/description.md
> +The [Resources demo](/Demos/WidgetsGallery/Demo/Scheduler/Resources/) describes how to assign resources. When assigned, they can also be used to group appointments. To implement this, specify the [gr
```suggestion
To group appointments by resources, specify the [groups[]](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/#groups) array. Each element of this array is [fieldExpr](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/resources/#fieldExpr) of a resource kind. The order of resource headers in the UI is the same as the order of the resource instances. Note that if the **resources** array has more than one element, grouping is nested. 
```

2021-05-31 07:56 UTC, RomanTsukanov commented on JSDemos/Demos/Scheduler/GroupOrientation/description.md
> +[Resources](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/resources/) are categories used to classify appointments. To understand what resources are, consider the following exam
We do need to make a connection between grouping and resources. However, this demo is about grouping, and we shouldn't dive deep into explaining the resources concept. The following description would suffice:

```suggestion
Appointments can be grouped by resources. This demo declares a single resource&mdash;Priority. Refer to the following demo for more information about resources and their configuration: [Resources](/Demos/WidgetsGallery/Demo/Scheduler/Resources/).
```

2021-05-31 07:56 UTC, RomanTsukanov commented on JSDemos/Demos/Scheduler/GroupOrientation/description.md
> +The Scheduler arranges group headers vertically (in a column) or horizontally (in a row). You can use the **views**.[groupOrientation](/Documentation/ApiReference/UI_Components/dxScheduler/Configurat
> The Scheduler arranges

Without "can", it reads as if the Scheduler chooses group orientation randomly.

> This property description includes default view orientation types.

It goes without saying. We better refer to the demo instead.


```suggestion
The Scheduler can arrange group headers vertically (in a column) or horizontally (in a row). You can use the **views**.[groupOrientation](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/views/#groupOrientation) property to set custom orientation for specific views. In this demo, the Work Week view type illustrates the difference between vertical and horizontal group orientations.
```

2021-05-31 07:56 UTC, RomanTsukanov commented on JSDemos/Demos/Scheduler/GroupOrientation/description.md
> +The [Resources demo](/Demos/WidgetsGallery/Demo/Scheduler/Resources/) describes how to assign resources. When assigned, they can also be used to group appointments. To implement this, specify the [gr
> The order of resource headers in the UI is the same as the order of the resource instances.

By "resource headers" you mean "group headers"? "the order of the resource instances" in which array?

> Note that if the **resources** array has more than one element, grouping is nested. 

Do you mean "if the **groups** array has more than one element"?

2021-05-31 10:49 UTC, RomanTsukanov approved these changes, later dismissed

2021-06-03 09:16 UTC, NikolaevaIrina commented on JSDemos/Demos/Scheduler/GroupOrientation/description.md
> +Appointments can be grouped by resources. This demo declares a single resource&mdash;Priority. Refer to the following demo for more information about resources and their configuration: [Resources](/D
```suggestion
Users can group appointments by resources. This demo declares a single resource&mdash;Priority. Refer to the following demo for more information about resources and their configuration: [Resources](/Demos/WidgetsGallery/Demo/Scheduler/Resources/).
```

2021-06-03 09:16 UTC, NikolaevaIrina commented on JSDemos/Demos/Scheduler/GroupOrientation/description.md
> +To group appointments by resources, specify the [groups[]](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/#groups) array. Each element of this array is [fieldExpr](/Documentation
```suggestion
To group appointments by resources, specify the [groups[]](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/#groups) array. Each element of this array is the [fieldExpr](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/resources/#fieldExpr) of a corresponding resource kind. The order of group headers in the UI mirrors the order of resource instances in the array. If the **groups[]** array contains more than one element, groups are nested. 
```

2021-06-03 09:16 UTC, NikolaevaIrina commented on JSDemos/Demos/Scheduler/GroupOrientation/description.md
> +The Scheduler can arrange group headers vertically (in a column) or horizontally (in a row). You can use the **views**.[groupOrientation](/Documentation/ApiReference/UI_Components/dxScheduler/Configu
```suggestion
The Scheduler can arrange group headers vertically (in a column) or horizontally (in a row). Use the **views**.[groupOrientation](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/views/#groupOrientation) property to set a custom orientation for specific views. This demo shows two Work Week views with different group orientations.
```

2021-06-04 08:30 UTC, dirk-pieterse submitted a review, later dismissed

2021-06-04 08:30 UTC, dirk-pieterse commented on JSDemos/Demos/Scheduler/GroupOrientation/description.md
> +To group appointments by resources, specify the [groups[]](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/#groups) array. Each element of this array is the [fieldExpr](/Documenta
```suggestion
To group appointments by resources, specify the [groups[]](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/#groups) array. Each element of this array is the [fieldExpr](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/resources/#fieldExpr) of a corresponding resource kind. The order of group headers in the UI is the same as items in the resource instances array. If the **groups[]** array contains more than one element, groups are nested. 
```

2021-06-04 12:41 UTC, RomanTsukanov approved these changes

2021-06-04 12:44 UTC, merged