Scheduler Group by Date: rewrite
DevExpress/devextreme-demos pull request #878
Opened 2021-05-19 11:58 UTC by pavel-2020

[Trello](https://trello.com/c/lTA2NdUk/1668-scheduler-demos-grouping-2-demos)
[Demo](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Scheduler/GroupByDate/React/Light/)

2021-05-24 09:14 UTC, AlexJameson commented on JSDemos/Demos/Scheduler/GroupByDate/description.md
> +In this demo, you can use the switch below the Scheduler to toggle the value of **groupByDate**.
```suggestion
In this demo, you can use the switch below the Scheduler to change the value of **groupByDate**.
```

2021-05-25 14:10 UTC, AlexJameson submitted a review, later dismissed

2021-05-27 10:32 UTC, RomanTsukanov requested changes

2021-05-27 10:32 UTC, RomanTsukanov commented on JSDemos/Demos/Scheduler/GroupByDate/description.md
> +If appointments are grouped by a resource, you can additionally group them by date first. To do this, set [groupByDate](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/#groupByDat
The same comment here: the reader doesn't know what resources are.

2021-06-07 08:20 UTC, RomanTsukanov approved these changes, later dismissed

2021-06-18 07:46 UTC, NikolaevaIrina commented on JSDemos/Demos/Scheduler/GroupByDate/description.md
> +When appointments are grouped by resources, you can additionally group them by date first. To do this, set [groupByDate](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/#groupByDa
```suggestion
When appointments are grouped by resources, you can additionally group them by date. To do this, set [groupByDate](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/#groupByDate) to **true**. You can also use the [same property](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/views/#groupByDate) for individual views. Note that Scheduler groups appointments by date only when the view's [groupOrientation](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/views/#groupOrientation) is *"horizontal"*.
```

2021-06-18 09:11 UTC, dirk-pieterse approved these changes

2021-06-18 11:50 UTC, merged