DataTree - add selectionChanged log for TreeList multiple selection demo
DevExpress/devextreme-demos pull request #879
Opened 2021-05-19 12:35 UTC by pomah33

Cherry Pick PRs:

-

Trello card: https://trello.com/c/gPIfdmWL/2460-add-selectionchanged-log-for-treelist-multiple-selection-demo

---

I added logging of current selected employees in [DataTree MultipleRowSelection Demo](https://js.devexpress.com/Demos/WidgetsGallery/Demo/TreeList/MultipleRowSelection/AngularJS/Light/)

| from that | to this |
|-|-|
| ![image](https://user-images.githubusercontent.com/84017191/118813187-913aae00-b8b7-11eb-9a59-53a4ab695cc2.png) | ![image](https://user-images.githubusercontent.com/84017191/118813308-aadbf580-b8b7-11eb-8aaf-a3da0b8ec4d0.png) |

2021-05-20 06:16 UTC, NickMitrokhin requested changes

2021-05-20 06:16 UTC, NickMitrokhin commented on JSDemos/Demos/TreeList/MultipleRowSelection/AngularJS/index.js
> +        }
I think it is better to use the same code style in all approaches:
```suggestion
        onSelectionChanged: function(e) {
            const data = e.component.getSelectedRowsData("all");
    
            if(data.length > 0)
                $scope.selectedItemsText = data.map(value => value.Full_Name).join(", ");
            else 
                $scope.selectedItemsText = "Nobody has been selected";
        }
```

2021-05-20 06:16 UTC, NickMitrokhin commented on JSDemos/Demos/TreeList/MultipleRowSelection/jQuery/index.js
> +        }
```suggestion
        onSelectionChanged: function(e) {
            const data = e.component.getSelectedRowsData("all");
            let selectedText = "Nobody has been selected";
            
            if(data.length > 0) {
                selectedText = data.map(value =>  value.Full_Name).join(", ");
            }
            $("#selected-items-container").text(selectedText);
        }
```

2021-05-20 06:16 UTC, NickMitrokhin commented on MVCDemos/Views/TreeList/MultipleRowSelection.cshtml
> +    }
```suggestion
    function selection_changed(e) {
        const data = e.component.getSelectedRowsData("all");
        let selectedText = "Nobody has been selected";
            
        if(data.length > 0) {
            selectedText = data.map(value =>  value.Full_Name).join(", ");
        }
        $("#selectedItemsContainer").text(selectedText);
    }
```

2021-05-20 06:16 UTC, NickMitrokhin commented on NetCoreDemos/Views/TreeList/MultipleRowSelection.cshtml
> +    }
```suggestion
 function selection_changed(e) {
        const data = e.component.getSelectedRowsData("all");
        let selectedText = "Nobody has been selected";
            
        if(data.length > 0) {
            selectedText = data.map(value =>  value.Full_Name).join(", ");
        }
        $("#selectedItemsContainer").text(selectedText);
    }
```

2021-05-20 17:11 UTC, NickMitrokhin submitted a review, later dismissed

2021-05-26 06:32 UTC, DX-man approved these changes

2021-05-27 06:52 UTC, NickMitrokhin approved these changes

2021-05-28 13:26 UTC, vconst approved these changes

2021-05-31 07:56 UTC, merged