Scheduler Customize Individual Views: rewrite
DevExpress/devextreme-demos pull request #912
Opened 2021-05-26 12:12 UTC by pavel-2020

[Trello](https://trello.com/c/ggGmCBjS/1669-scheduler-demos-customization-3-demos)
[Demo](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Scheduler/CustomizeIndividualViews/jQuery/Light/)

2021-06-01 07:44 UTC, AlexJameson commented on JSDemos/Demos/Scheduler/CustomizeIndividualViews/description.md
> +is that they group appointments by resources and set the [dateCellTemplate](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/views/#dateCellTemplate). In addition, the *"workWeek"*
```suggestion
This demo has two customized views: *"week"* and *"workWeek"*. They group appointments by resources and specify the [dateCellTemplate](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/views/#dateCellTemplate). In addition, the *"workWeek"* view specifies the [startDayHour](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/views/#startDayHour) and [endDayHour](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/views/#endDayHour) values.
```

2021-06-01 07:44 UTC, AlexJameson commented on JSDemos/Demos/Scheduler/CustomizeIndividualViews/description.md
> +To add a customized view, create an object in the [views[]](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/views) array. In this object, you should specify the view's [type](/Doc
We can be much more straightforward here:

```suggestion
To customize a view, specify its settings in an object in the [views[]](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/views) array. You should specify the view's [type](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/views/#type) and other properties that override global Scheduler configuration.
```

2021-06-01 11:39 UTC, AlexJameson approved these changes, later dismissed

2021-06-01 11:39 UTC, AlexJameson commented on JSDemos/Demos/Scheduler/CustomizeIndividualViews/description.md
> +To customize a view, configure its settings in an object of the [views[]](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/views) array. You should specify the view's [type](/Docum
An object should be an element of the **views[]** array that means this object is **in** the array, right?

```suggestion
To customize a view, configure its settings in an object in the [views[]](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/views) array. You should specify the view's [type](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/views/#type) and other properties that override global Scheduler settings.
```

2021-06-02 10:39 UTC, RomanTsukanov requested changes

2021-06-02 10:39 UTC, RomanTsukanov commented on JSDemos/Demos/Scheduler/CustomizeIndividualViews/description.md
> +To customize a view, configure its settings in an object of the [views[]](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/views) array. You should specify the view's [type](/Docum
```suggestion
To customize a view, configure its settings in an object of the [views[]](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/views) array. You should specify the view's [type](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/views/#type) and other properties to override global view settings.
```

2021-06-02 10:39 UTC, RomanTsukanov commented on JSDemos/Demos/Scheduler/CustomizeIndividualViews/description.md
> +This demo has two customized views: *"week"* and *"workWeek"*. They group appointments by resources and specify the [dateCellTemplate](/Documentation/ApiReference/UI_Components/dxScheduler/Configurat
```suggestion
This demo shows four views, two of which (Week and Work Week) are customized. Both customized views [group appointments](/Demos/WidgetsGallery/Demo/Scheduler/GroupOrientation/) by [resources](/Demos/WidgetsGallery/Demo/Scheduler/Resources/) and use the [dateCellTemplate](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/views/#dateCellTemplate) to change the appearance of date cells. In addition, the [startDayHour](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/views/#startDayHour) and [endDayHour](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/views/#endDayHour) properties are used to narrow down the time window on the Work Week view.
```

2021-06-03 08:12 UTC, RomanTsukanov submitted a review, later dismissed

2021-06-04 22:53 UTC, Abadzhev commented on JSDemos/Demos/Scheduler/CustomizeIndividualViews/description.md
> +This demo shows four views, two of which (Week and Work Week) are customized. Both customized views [group appointments](/Demos/WidgetsGallery/Demo/Scheduler/GroupOrientation/) by [resources](/Demos/
`... two of which ...` - sign of a complicated sentence. You can even put a period after `four views` and start the next sentence with `Week and Work Week views`. 

`are customized` - passive. 

'properties are used' - passive. 

The list of changes is written as a narrative, where I would suggest a more structured approach (a list). 

So here's the suggestion that fixes all those comments. 

```suggestion
This demo customizes two views - Week and Work Week - in the following manner: 

* Both views [group appointments](/Demos/WidgetsGallery/Demo/Scheduler/GroupOrientation/) by [resources](/Demos/WidgetsGallery/Demo/Scheduler/Resources/).
* Both views use the [dateCellTemplate](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/views/#dateCellTemplate) to change the appearance of date cells.
* The Work Week view changes the [startDayHour](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/views/#startDayHour) and [endDayHour](/Documentation/ApiReference/UI_Components/dxScheduler/Configuration/views/#endDayHour) properties to limit the time range.

Day and Month views use default settings.
```

2021-06-07 09:15 UTC, dirk-pieterse approved these changes

2021-06-07 12:02 UTC, merged